label,log,package
1,g++: error: '-march=pentium3': ISA string must begin with rv32 or rv64 make[1]: *** [mocks_real.make:99: obj/mocks_real_Release/mocks_real.o] Error 1 make: *** [Makefile:159: mocks_real] Error 2,0ad
1,"error: #error ""No support for this architecture (yet)"" Makefile:269: *** Unsupported target architecture.",ageisub
5,[  924.609180][T16993] Out of memory: Killed process 16993 (pandoc) total-vm:1079089668kB  anon-rss:2877596kB  file-rss:0kB  shmem-rss:0kB  UID:399 pgtables:9740kB oom_score_adj:0 ,amsynth
5,#warning You are compiling libardour on a platform for which ardour/cycles.h needs work Build failed -> task in 'libardour' failed with exit status 1 (run with -v to display more information),ardour
2,error: failed to run custom build command for `ring v0.16.20` ,atuin
3,AUBIO-TESTS ERROR: not enough arguments  running tests AUBIO ERROR: source_avcodec: Aborted opening null path AUBIO ERROR: source_avcodec: Failed opening  (No such file or directory),aubio
2,CMake Error at cmake-proxies/cmake-modules/Findvst3sdk.cmake:56 (message): Failed to build VST3SDK Configuring incomplete  errors occurred!,audacity
3,"The following tests FAILED: 	  1 - bear::func_test (Timeout) Errors while running Ctest",Bear
2,/bin/sh: line 1: git: command not found make: *** [Makefile:181: obj/filter/tree_test.ok] Error 139,bird
1,"meson.build:90:1: ERROR: Problem encountered: Architecture ""riscv64"" is not supported.",boxfort
5,AssertionError: MemoryError not raised,breezy
6,lto-wrapper: fatal error: make returned 2 exit status ,bulk_extractor
5,[  111.621611][ T4183] Out of memory: Killed process 4183 (qemu-riscv64) total-vm:1078697528kB  anon-rss:3486616kB  file-rss:0kB  shmem-rss:0kB  UID:399 pgtables:9108kB,bup
3,deviation in file beamfsh1.dat line: 103 reference value: -5.943977e-09 value: -3.410154e-10               absolute error: 5.602962e-09               largest value within same block: 1.276463e-07               relative error w.r.t. largest value within same block: 4.389443 %,ccx
6,lto-wrapper: fatal error: make returned 2 exit status,clanlib
2,Module build failed (from ./node_modules/babel-loader/lib/index.js)： NonErrorEmittedError: (Emitted value instead of an instance of Error) [object Object] webpack 5.74.0 compiled with 15 errors in 219686 ms,cockpit
2,Module build failed (from ./node_modules/babel-loader/lib/index.js): NonErrorEmittedError: (Emitted value instead of an instance of Error) [object Object] webpack compiled with 8 errors,cockpit-d-installer
8,error: File not found: /home/abuild/rpmbuild/BUILDROOT/collectd-5.9.0.130.g2f3c9e-1.3.riscv64/usr/lib64/collectd/nut.so  error: File not found: /home/abuild/rpmbuild/BUILDROOT/collectd-5.9.0.130.g2f3c9e-1.3.riscv64/usr/lib64/collectd/nut.la,collectd
4,/usr/lib64/gcc/riscv64-suse-linux/9/../../../../riscv64-suse-linux/bin/ld: /tmp/cc7rEUJG.ltrans5.ltrans.o: in function `.L0 ': /home/abuild/rpmbuild/BUILD/coturn-4.6.1/src/apps/common/ns_turn_utils.c:606: undefined reference to `FIPS_mode',coturn
3,"The following tests FAILED: 	 13 - TestCondition (Failed) Errors while running Ctest",cppcheck
1,./dapl/udapl/linux/dapl_osd.h:55:2: error: #error UNDEFINED ARCH   #error UNDEFINED ARCH,dapl
1,./dapl/udapl/linux/dapl_osd.h:55:2: error: #error UNDEFINED ARCH   #error UNDEFINED ARCH,dapl-debug
6,service/debugger/debugger.go:32:2: found packages native (dump_linux.go) and your_linux_architecture_is_not_supported_by_delve (support_sentinel_linux.go) in /home/abuild/rpmbuild/BUILD/delve-1.20.0/pkg/proc/native,delve
4,dh.cc:40:23: error: 'get_dh2048' was not declared in this scope,drops
8,cc1: fatal error: renesas/*.dts: No such file or directory,dtb-riscv64
2,ERROR in ./node_modules/matrix-react-sdk/res/img/feather-customised/warning-triangle.svg      Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):      NonErrorEmittedError: (Emitted value instead of an instance of Error) [object Object],element-web
3,ERROR: One or more eunit tests failed. ERROR: eunit failed while processing /home/abuild/rpmbuild/BUILD/rebar-2.6.4+git20180201.b6d3094: rebar_abort,erlang-rebar-testsuite
4,memory_allocator.h:119:15: error: 'sys_mmap' was not declared in this scope memory_allocator.h:145:7: error: 'sys_munmap' was not declared in this scope; did you mean 'munmap'?,EternalTerminal
1,"src/execstack: ""test""'s architecture is not supported",execstack
4,uninit.c:302:17: error: '_FPU_MASK_IM' undeclared (first use in this function),f2c
1,/home/abuild/rpmbuild/BUILD/fdo-client-1.0.0+git20210816.baa09b5/crypto/openssl/openssl_key_exchange_ecdh.c:508:9: error: 'EC_POINT_get_affine_coordinates_GFp' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]    508 |         if (EC_POINT_get_affine_coordinates_GFp(group  Sh_se_point  Shx_bn ,fdo-client
5,[ 2442.198534][ T8997] Out of memory: Killed process 8950 (Setup) total-vm,ghc-authenticate-oauth
5,[ 3028.161795][T10708] Out of memory: Killed process 10661 (Setup) total-vm,ghc-citeproc
5,[ 1968.000306][ T7607] Out of memory: Killed process 7560 (Setup) total-vm,ghc-cryptonite-conduit
5,[ 3479.90606][T9641] Out of memory: Killed process 9605 (Setup) total-vm,ghc-dhall
5,[ 1726.067221][ T5580] Out of memory: Killed process 5580 (ghc) total-vm,ghc-ed25519
5,[ 2808.591447][ T9619] Out of memory: Killed process 9539 (Setup) total-vm:,ghc-feed
5,[ 2291.069182][ T8378] Out of memory: Killed process 8331 (Setup) total-vm,ghc-hedgehog
5,[ 2332.020837][ T8747] Out of memory: Killed process 8689 (Setup) total-vm,ghc-hslua-module-doclayout
5,[ 1373.695587][ T6235] Out of memory: Killed process 6199 (Setup) total-vm,ghc-kan-extensions
1,error: line 62: Version required: Requires:       ghc-compiler = Building target platforms: riscv64-suse-linux Building for target riscv64-suse-linux,ghc-pandoc-lua-marshal
5,[ 4869.188984][T15464] Out of memory: Killed process 15417 (Setup) total-vm,ghc-sandwich
5,[ 3657.404595][T11779] Out of memory: Killed process 11699 (Setup) total-vm,ghc-skylighting-core
1,error: line 43: Version required: Requires:       ghc-compiler = Building target platforms: riscv64-suse-linux Building for target riscv64-suse-linux,ghc-tasty-hunit
5,[ 1919.243355][ T7313] Out of memory: Killed process 7255 (Setup) total-vm,ghc-tasty-quickcheck
5,[ 2294.193399][ T8513] Out of memory: Killed process 8466 (Setup) total-vm,ghc-turtle
5,[ 3810.194259][T13007] Out of memory: Killed process 9949 (Setup) total-vm,ghc-wai-app-static
5,[ 3087.889015][T10606] Out of memory: Killed process 10548 (Setup) total-vm,ghc-xml-hamlet
3,make[4]: *** [Makefile:723: test-suite.log] Error 1 make[3]: *** [Makefile:831: check-TESTS] Error 2,gphoto
2,ValueError: LDAP Setup failed,gssproxy
2,error: failed to run custom build command for `ring v0.16.20`,gstreamer-plugins-rs
1,g++: error: unrecognized command-line option ‘-msse2’ g++: error: unrecognized command-line option ‘-mfpmath=sse’,guitarix
6,make: *** [Makefile:169: all] Error 2,hashlink
6,1 out of 1 hunk FAILED -- saving rejects to file vendor/nix/.cargo-checksum.json.rej patching file vendor/nix/src/sys/ioctl/linux.rs Hunk #1 FAILED at 33. 1 out of 1 hunk FAILED -- saving rejects to file vendor/nix/src/sys/ioctl/linux.rs.rej,helvum
3,make[5]: *** [Makefile:1052: test-suite.log] Error 1 make[4]: *** [Makefile:1160: check-TESTS] Error 2,hfst
4,linux/trace.c:332:5: error: unknown type name 'HEADERS_STRUCT' linux/trace.c:444:17: error: 'MAX_INSTR_SZ' undeclared (first use in this function) linux/trace.c:444:13: error: unused variable 'buf' [-Werror=unused-variable],honggfuzz
1,"#error ""No support for this architecture (yet)""",howl
1,error: #error You are trying to use x86 context switching on a non-x86 platform. Your platform may be supported with the CMake option HPX_WITH_GENERIC_CONTEXT_COROUTINES=ON.,hpx
4,turnrest.c:164:9: error: void value not ignored as it ought to be    164 |         curl_easy_setopt(curl  api_http_get ? CURLOPT_HTTPGET : CURLOPT_POST  1);,janus-gateway
2,error: failed to run custom build command for `ring v0.16.20`,juliaup
4,error[E0425]: cannot find value `AVG_RANGE_COMP_REQ` in this scope error[E0425]: cannot find value `AVG_RANGE_COMP_REQ` in this scope,kanidm
1,kBuild/env.sh: unknown cpu/arch - riscv64,kbuild
1,# error Unsupported architecture,kcov
2,"error: #error ""No default crashkernel reservation for your architecture!"" error: 'CAN_REDUCE_CPUS' was not declared in this scope error: 'DEF_RESERVE_KB' was not declared in this scope; did you mean 'ADD_RESERVE_KB'?",kdump
3,"FAIL	github.com/keybase/client/go/kbfs/test	600.701s",keybase-client
3,Errors while running Ctest,kicad
8,touch: cannot touch '_output/bin/prerelease-lifecycle-gen': No such file or directory,kubernetes1.20
8,touch: cannot touch '_output/bin/prerelease-lifecycle-gen': No such file or directory,kubernetes1.21
8,touch: cannot touch '_output/bin/prerelease-lifecycle-gen': No such file or directory,kubernetes1.22
8,touch: cannot touch '_output/bin/prerelease-lifecycle-gen': No such file or directory,kubernetes1.23
8,touch: cannot touch '_output/bin/prerelease-lifecycle-gen': No such file or directory,kubernetes1.24
2,error: failed to run custom build command for `ring v0.16.20`,kubie
3,make[5]: *** [Makefile:973: test-suite.log] Error 1 make[4]: *** [Makefile:1081: check-TESTS] Error 2,lasso
4,src/config.h:365:53: error: unknown type name 'La_regs' src/audit.c:134:49: error: unknown type name 'La_retval',latrace
4,../govirt/ovirt-utils.c: In function ‘ovirt_rest_xml_node_get_str_array_from_path’: ../govirt/ovirt-utils.c:137:9: error: cast increases required alignment of target type [-Werror=cast-align],libgovirt
4,/home/abuild/rpmbuild/BUILD/libjxl-0.8.1/lib/jxl/enc_xyb.cc:223:21: error: variable 'std::atomic<bool> ok' has initializer but incomplete type    223 |   std::atomic<bool> ok{true};,libjxl
1,CMake Error at CMakeLists.txt:82 (message):    Unknown or unsupported processor: riscv64.  Override by setting    OQS_PERMIT_UNSUPPORTED_ARCHITECTURE=ON,liboqs
2,LifeLines requires a curses implementation with wide character support! + make -j16 make: *** No targets specified and no makefile found.  Stop.,lifelines
2,configure: error: Package requirements (luajit) were not met: Package 'luajit'  required by 'virtual:world'  not found,love
4,error: 'class Quotient::AccountSettings' has no member named 'accessToken'; did you mean 'clearAccessToken'?,matrix-quaternion
3,error: 1 target failed:      `--test alternative_backends`,mdbook
3,# Ran 220 tests  10 skipped  18 failed.,mercurial-extension-hg-evolve
8,"CMake Error at cmake/Modules/FindLua.cmake:27 (add_subdirectory):    add_subdirectory given source ""lib/lua"" which is not an existing directory.",minetest
4,pkg/drivers/kvm/domain.go:67:53: undefined: domainTmpl,minikube
4,dns_utils.cpp:590:22: error: 'record_count' was not declared in this scope dns_utils.cpp:597:23: error: 'good_record' was not declared in this scope; did you mean 'good_records'?,monero
1,net_ssl.cpp:216:35: warning: 'EC_KEY* EC_KEY_new()' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations],monero-gui
8,cp: cannot stat './../../class/lib/build-linux/tmp/gensources.exe': No such file or directory,mono-core
4,SelfSignedCertificate.cpp:45:29: error: 'CRYPTO_MEM_CHECK_ON' was not declared in this scope SelfSignedCertificate.cpp:45:13: error: 'CRYPTO_mem_ctrl' was not declared in this scope; did you mean 'CRYPTO_memcmp'?,mumble
1,"Makefile:144: *** CPU type ""riscv64"" not supported.  Please file bug report at 'https://github.com/mupen64plus/mupen64plus-core/issues'.  Stop.",mupen64plus
2,Run-time dependency luajit found: NO (tried pkgconfig and cmake),naev
2,error: failed to run custom build command for `ring v0.16.20`,ncspot
5,c++: internal compiler error: Segmentation fault signal terminated program cc1plus,neochat
4,simd_generic.hpp:324:56: error: cannot convert 'const ngcore::SIMD<double  1>' to 'double' in initialization,netgen
4,src/poddlthread.cpp:65:31: error: 'CURLOPT_PROGRESSFUNCTION' is deprecated: since 7.32.0. Use CURLOPT_XFERINFOFUNCTION [-Werror=deprecated-declarations],newsboat
8,install: cannot stat 'nmon': No such file or directory,nmon
2,vendor/golang.org/x/exp/shiny/driver/x11driver/buffer.go:111:9: undefined: shmClose vendor/golang.org/x/exp/shiny/driver/x11driver/screen.go:328:23: undefined: shmOpen, noisetorch
2,CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):    Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR),nomacs
6,CMakeFiles/Makefile2:2682: CMakeFiles/notcurses.3.man.dir/all] Error 2,notcurses
8,cpio: gcc-9.2.1+git749/libgcc/libgcc2.c: Cannot stat: No such file or directory,ocserv
8,make[3]: *** No rule to make target 'param.riscv64_linux26.h'  needed by 'param.h.new'.  Stop.,openafs
3,"The following tests FAILED: 	 82 - test_regressions_1 (Subprocess killed) 	 83 - test_regressions_221 (Subprocess killed)  	213 - inchiSteffen_PubChem.smi_Test (Timeout) 	215 - pytest_sym (Timeout) 	223 - pybindtest_bindings (Failed) Errors while running CTest",openbabel
6,No buildstatus set  either the base system is broken (kernel/initrd/udev/glibc/bash/perl) or the build host has a kernel or hardware problem…,openjfx8
4,operf_utils.cpp:1423:2: error: 'rmb' was not declared in this scope,oprofile
4,base64.c:89:36: error: 'i' may be used uninitialized [-Werror=maybe-uninitialized] base64.c:94:20: error: 'skip' may be used uninitialized [-Werror=maybe-uninitialized],pam_p11
2,error: failed to run custom build command for `ring v0.16.20`,parsec
2,error: failed to run custom build command for `ring v0.16.20`,parsec-tool
8,make: *** No rule to make target 'include/generic/Types.inc'  needed by 'api/thunks.o'.  Stop.,perl-Prima
6,Fatal SIMPLE-ERROR:    please implement make: *** [Makefile:47: bin/pgloader] Error 1,pgloader
1,dhparam: Unknown option: -C dhparam: Use -help for summary.,pound
1,libglfork.cpp:1028:6: error: ifunc is not supported on this target,primus
1,"/usr/lib64/python3.11/random.py:436: in sample      raise TypeError(""Population must be a sequence.  "" E   TypeError: Population must be a sequence.  For dicts or sets  use sorted(d).",python-ansiwrap
1,"AssertionError: '[mp4] muxer does not support non seekable output' not found in ""no container format 'mp4'""",python-av
6,ConnectionRefusedError: [Errno 111] Connection refused,python-avro
4,stdalign_check.c:13:9: error: unused variable ‘alignment’ [-Werror=unused-variable] stdalign_check.c:9:24: error: unused variable ‘test’ [-Werror=unused-variable],python-awscrt
6,Badness 1000 exceeds threshold 999  aborting,python-azure-communication-networktraversal
6,Badness 1000 exceeds threshold 999  aborting,python-azure-mgmt-recoveryservicessiterecovery
6,Badness 1000 exceeds threshold 999  aborting,python-azure-mgmt-servicefabricmanagedclusters
6,Badness 1000 exceeds threshold 999  aborting,python-azure-multiapi-storage
6,Badness 1000 exceeds threshold 999  aborting.,python-brewer2mpl
3,FAILED test_runtime.py::RuntimeGoingWrongTestCase::test_duplication_and_runtime_malformed,python-calmjs
4,AttributeError: module 'inspect' has no attribute 'getargspec',python-cepa
4,TypeError: tuple indices must be integers or slices  not str TypeError: __dict__ must be set to a dictionary  not a 'NoneType',python-cerealizer
3,cpplint_unittest.py:6501: AssertionError,python-cpplint
3,tests/test_subprocess.py:84: AssertionError,python-curio
1,KeyError: 'INPLACE_ADD',python-cx_Freeze
8,cytoolz/dicttoolz.c:211:9: fatal error: longintrepr.h: No such file or directory,python-cytoolz
3,"FAILED test_datadiff.py::test_diff_set - assert ""--- x\n+++ y...n 3 \n 7 \n])... FAILED test_datadiff.py::test_diff_frozenset - assert ""--- x\n+++ y...n 3 \n …",python-datadiff
3,FAILED testing/test_metadata.py::TestBasenameMeta::test_noversion_sameproject FAILED testing/test_metadata.py::TestBasenameMeta::test_sort_sameproject_links,python-devpi-common
3,FAIL: testDiffMain (diff_match_patch.tests.diff_match_patch_test.DiffTest) AssertionError: False is not true,python-diff-match-patch
3,FAILED tests/test_django.py::TestStaticFiles::test_find_with_glob - re.error:... FAILED tests/test_django.py::TestStaticFiles::test_find_with_recursive_glob,python-django-assets
3,FAILED tests/test_handlers.py::AxesDatabaseHandlerTestCase::test_handler - As... FAILED tests/test_logging.py::AccessLogTestCase::test_log_data_truncated - ax…,python-django-axes
4,ERROR: test_view_dynamic (tagging.tests.tests.TestTaggedObjectList.test_view_dynamic) raise source.error('global flags not at the start ' re.error: global flags not at the start of the expression at position 14,python-django-tagging
8,editdistance/bycython.cpp:216:9: fatal error: longintrepr.h: No such file or directory,python-editdistance
4,packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier),python-efilter
8,efl/eo/efl.eo.c:248:9: fatal error: longintrepr.h: No such file or directory,python-efl
3,FAILED tests/test_node_pool.py::test_threading_test[1] - assert 4633 >= 10000 FAILED tests/test_node_pool.py::test_threading_test[8] - assert 3108 >= 10000,python-elastic-transport
3,FAILED eliot/tests/test_filter.py::MainTests::test_default - AttributeError: …,python-eliot
1,ImportError: cannot import name 'sre_parse' from 're' (/usr/lib64/python3.11/re/__init__.py),python-exrex
3,FAILED tests/test_pyi_files.py::test_pyi_file[tests/type_comments.pyi] - asse…,python-flake8-pyi
8,cc1: fatal error: frozendict/src/3_11/frozendictobject.c: No such file or directory,python-frozendict
3,FAILED test/test_holiday_base.py::TestAllInSameYear::test_all_countries - Att…,python-holidays
3,FAILED test_ece.py::TestEce::test_derive_key_invalid_mode - AttributeError: '…,python-http-ece
6,No buildstatus set  either the base system is broken (kernel/initrd/udev/glibc/bash/perl) [90344s] or the build host has a kernel or hardware problem…,python-i3ipc
3,FAILED influxdb/tests/client_test.py::TestInfluxDBClient::test_write_gzip - A…,python-influxdb
4,jp_exception.cpp:524:23: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘frame’; did you mean ‘cframe’? jp_exception.cpp:552:36: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’},python-JPype1
3,FAILED jsonweb/tests/test_decode.py::TestJsonWebObjectDecoder::test_bad__init__raises_error FAILED jsonweb/tests/test_decode.py::TestJsonWebObjectDecoder::test_class_kw_args_are_optional,python-JsonWeb
3,FAILED tests/unit/utils/test_scp.py::TestScp::test_scp_user_def_progress FAILED tests/unit/utils/test_scp.py::TestScp::test_scp_user_def_progress_args_2,python-junos-eznc
3,SKIPPED [1] test/test_admin_integration.py:13: ACL features require broker >=0.11 SKIPPED [1] test/test_admin_integration.py:89: Describe config features require broker >=0.11,python-kafka-python
3,FAILED kajiki/tests/test_ir.py::TestBasic::test - TypeError: code() argument ... FAILED kajiki/tests/test_ir.py::TestSwitch::test_basic - TypeError: code() ar…,python-Kajiki
4,_line_profiler.c:5627:46: error: invalid use of incomplete typedef ‘PyFrameObject’ {aka ‘struct _frame’},python-line_profiler
1,RuntimeError: Cannot install on Python version 3.11.1; only versions >=3.7 <3.11 are supported.,python-llvmlite
8,lws.bycython.cpp:196:9: fatal error: longintrepr.h: No such file or directory,python-lws
3,FAIL: test_Cookie_iterator (test.test_cookies.CookieTests.test_Cookie_iterator),python-mechanize
2,error: failed to run custom build command for `ring v0.16.20`,python-mitmproxy-wireguard
3,FAILED tests/test_compute_hash.py::TestComputeHash::test_ntowfv1 - ValueError... FAILED tests/test_compute_hash.py::TestComputeHash::test_ntowfv2 - ValueError…,python-ntlm-auth
4,pybind11.h:1892:14: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’},python-openmesh
3,ERROR: test_is_legacy_version (tests.test_version.TestOpenwrtLuciRPC) Test comparing versions works as expected.,python-openwrt-luci-rpc
4,TypeError: not all arguments converted during string formatting,python-oslo.policy
4,TypeError: not all arguments converted during string formatting,python-oslo.versionedobjects
3,ERROR parsimonious/tests/test_benchmarks.py ERROR parsimonious/tests/test_expressions.py ERROR parsimonious/tests/test_grammar.py ERROR parsimonious/tests/test_nodes.py,python-parsimonious
3,FAILED test/test_filepath.py::Test_validate_filepath::test_exception_invalid_char[17DOJ6bKqfdiULG0LywrS37oFh7LAmeHJJyGieLRVf4xjHkenEuiBa8P0zwknBE1\x0017DOJ6bKqfdiULG0LywrS37oFh7LAmeHJJyGieLRVf4xjHkenEuiBa8P0zwknBE1] FAILED test/test_filepath.py::Test_sanitize_filepath::test_normal_str[universal-AA\x00B--AAB0],python-pathvalidate
3,FAILED tests/test_cli_sync.py::test_force_files_with_dot_in_extension - asser... FAILED tests/test_cli_sync.py::test_pip_install_flags[cli_flags6-expected_install_flags6],python-pip-tools
3,FAILED tests/test_local.py::TestLocalMachine::test_iter_lines_timeout - asser…,python-plumbum
1,Sorry  but pony 0.7.16 requires Python of one of the following versions: 3.6-3.10. You have version 3.11.1,python-pony
4,ValueError: invalid mode: 'U',python-pprintpp
3,FAILED pscript/tests/test_parser1.py::TestExpressions::test_import - Assertio…,python-pscript
8,E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory E: [null-sink] util.c: Failed to connect to system bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory,python-pulsectl
4,pyblake2module.c:699:27: error: lvalue required as left operand of assignment,python-pyblake2
3,FAILED pyct/tests/test_report.py::test_report_gives_package_version - Asserti…,python-pyct
3,FAILED tests/test_build.py::test_logo - assert [],python-pydata-sphinx-theme
8,pyemd/emd.cpp:200:9: fatal error: longintrepr.h: No such file or directory,python-pyemd
8,src_c/pypm.c:209:9: fatal error: longintrepr.h: No such file or directory,python-pygame
3,FAILED kmip/tests/unit/services/server/crypto/test_engine.py::TestCryptographyEngine::test_mac_with_cryptographic_failure,python-PyKMIP
3,FAILED tests/test_pyp.py::test_examples - pyp.PypError: Code raised the follo... FAILED tests/test_pyp.py::test_user_error - AssertionError: Regex pattern did…,python-pyp
3,FAILED tests/test_i18n.py::TestTranslations::test_ldgettext - AttributeError:... FAILED tests/test_i18n.py::TestTranslations::test_ldngettext - AttributeError…,python-pyramid
1,AttributeError: module 'numpy' has no attribute 'float',python-pyreadstat
3,SKIPPED [1] tests/PyroTests/test_naming2.py:342: dbm must be available SKIPPED [1] tests/PyroTests/test_naming2.py:100: dbm must be available,python-Pyro4
3,FAILED scss/tests/test_expression.py::test_reference_operations - re.error: g... FAILED scss/tests/test_expression.py::test_functions - scss.errors.SassSyntax…,python-pyScss
8,Modules/_sha3/backport.inc:78:10: fatal error: pystrhex.h: No such file or directory,python-pysha3
3,FAILED ../tests/test_cap_operations.py::test_iterate_empty_psml_capture - ass…,python-pyshark
3,FAILED test_junit_classname.py::flake-8::FLAKE8 - AttributeError: 'Applicatio…,python-pytest-flake8
1,_pycrfsuite.cpp:18056:23: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’ _pycrfsuite.cpp:18058:23: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’,python-python-crfsuite
3,FAILED tests/test_scheduler.py::SchedulerTestCase::test_04_schedule_ten - Ass…,python-python-crontab
8,src/_rtmidi.cpp:243:9: fatal error: longintrepr.h: No such file or directory,python-python-rtmidi
4,ERROR: testQuotes (pytils.test.test_typo.RulesTestCase.testQuotes) Unit-test for quotes rule re.error: global flags not at the start of the expression at position 14,python-pytils
3,FAILED test/test_pytools.py::test_obj_array_vectorize - AttributeError: modul…,python-pytools
8,src/quicktions.c:209:9: fatal error: longintrepr.h: No such file or directory,python-quicktions
8,sasl/saslwrapper.cpp:196:9: fatal error: longintrepr.h: No such file or directory,python-sasl
6,error: subprocess-exited-with-error error: metadata-generation-failed,python-scipy
6,Badness 1132 exceeds threshold 999  aborting,python-securesystemslib
4,siplib.c:13750:22: error: invalid use of undefined type 'struct _frame',python-sip4
4,AttributeError: type object 'op' has no attribute 'pop_jump_if_true',python-skyfield
3,FAILED tests/test_path.py::TestPath::test_read_text - ValueError: invalid mod... FAILED tests/test_util.py::TestSphinxTesting::test_TestApp_when_copy_srcdir_to_tmpdir,python-sphinx-testing
1,utilsextension.c:22347:24: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’ utilsextension.c:22349:22: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’,python-tables
3,/var/tmp/rpm-tmp.o4A8wa: line 233:  6662 Segmentation fault      PYTHONPATH=${PYTHONPATH:+$PYTHONPATH:}/home/abuild/rpmbuild/BUILDROOT/python-tesserocr-2.5.2-3.2.riscv64/usr/lib/python3.8/site-packages PYTHONDONTWRITEBYTECODE=1 pytest-3.8 --ignore=_build.python38 --ignore=_build.python39 --ignore=_build.python311 --ignore=_build.python310 -v -k 'not test_LSTM_choices',python-tesserocr
3,ERROR test_aio.py - AttributeError: module 'asyncio' has no attribute 'corout... ERROR test_buffered_transport.py - AttributeError: module 'asyncio' has no at…,python-thriftpy2
3,FAILED test/test_as_future.py::test_as_future_coroutine[asyncio] - ImportErro... FAILED test/test_call_later.py::test_explicit_reactor_coroutine[asyncio] - Im…,python-txaio
3,FAILED tests/testsuite.py::XMLTestRunnerTestCase::test_basic_unittest_constructs FAILED tests/testsuite.py::XMLTestRunnerTestCase::test_unexpected_success - A…,python-unittest-xml-reporting
1,ERROR: test_coroutine_error (urwid.tests.test_event_loops.AsyncioEventLoopTest.test_coroutine_error) AttributeError: module 'asyncio' has no attribute 'coroutine',python-urwid
4,ERROR test_whatever.py - TypeError: code expected at least 16 arguments  got 14,python-whatever
3,FAILED tests/test_callable.py::test_callable_attributes - AttributeError: typ... FAILED tests/test_wire.py::test_default_wire - AttributeError: type object 'm…,python-wirerope
1,ERROR pytest/test_std.py - KeyError: '3.11',python-xdis
3,FAILED tests/test_xkcdpass.py::TestEntropyInformation::test_entropy_printout_valid_input,python-xkcdpass
3,Error in test test_with_syslog (ZConfig.components.logger.tests.test_logger.TestConfig.test_with_syslog) AttributeError: module 'socket' has no attribute 'SocketError',python-Zconfig
5,g++: internal compiler error: Segmentation fault signal terminated program cc1plus,qbs
8,types.h:11:10: fatal error: quadmath.h: No such file or directory,qcdloop
6,Error: unable to perform an operation on node 'rabbit@localhost'. Please see diagnostics information and suggestions below.,rabbitmq-c
3,"The following tests FAILED:  	 16 - exhaustive1_test (Timeout) 	 17 - exhaustive2_test (Timeout) 	 19 - exhaustive_test (Timeout) Errors while running Ctest",re2
1,NoMethodError: undefined method `exists?' for File:Class,rubygem-passenger
6,1 out of 1 hunk FAILED -- saving rejects to file vendor/tss-esapi-sys/.cargo-checksum.json.rej,rust-keylime
2,error: failed to run custom build command for `ring v0.16.20`,rustscan
6,error: Bad exit status from /var/tmp/rpm-tmp.iMySza (%build),sbcl
1,scitokens_internal.cpp:59:90: error: 'void EC_KEY_free(EC_KEY*)' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations] scitokens_internal.cpp:520:51: error: 'const EC_POINT* EC_KEY_get0_public_key(const EC_KEY*)' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations] scitokens_internal.cpp:527:45: error: 'int EC_POINT_get_affine_coordinates_GFp(const EC_GROUP*  const EC_POINT*  BIGNUM*  BIGNUM*  BN_CTX*)' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations],scitokens-cpp
4,GNUmakefile:67: *** multiple target patterns.  Stop.,seamonkey
3,make[6]: *** [Makefile:820: test-suite.log] Error 1 make[5]: *** [Makefile:928: check-TESTS] Error 2,softhsm
2,CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):    Could NOT find LuaJIT (missing: LUAJIT_LIBRARY LUAJIT_INCLUDE_DIR),solarus
1,../../utils/parse_plt.h:134:2: error: #error Unknown architecture    134 | #error Unknown architecture,spindle
6,make: *** [Makefile:159: all] Error,stellarium
2,configure: error: Package requirements (luajit) were not met: Package 'luajit'  required by 'virtual:world'  not found,sysbench
4,/home/abuild/rpmbuild/BUILD/thinkfan-1.3.1/src/fans.cpp:192: undefined reference to `__atomic_fetch_sub_1',thinkfan
2,error: failed to run custom build command for `ring v0.16.20`,tiny
1,../src/tup/platform.c:64:2: error: #error Unsupported cpu architecture. Please add support in tup/platform.c 64 | #error Unsupported cpu architecture. Please add support in tup/platform.c,tup
2,[92m *[0m Checking for Zlib... [91m *[0m Configure failed. error was: undefined method `exists?' for File:Class,tupitube
1,cc: error: '-march=native': ISA string must begin with rv32 or rv64 CMake Error at CMakeLists.txt:174 (string):,vectorscan
3,"Failures:  	From test_vim9_script.vim: 	Found errors in Test_reject_declaration(): 	Caught exception in Test_reject_declaration(): Vim(call):E109: Type mismatch; expected list<number> but got list<any> @ command line..script /home/abuild/rpmbuild/BUILD/vim-9.0.1307/src/testdir/runtest.vim[569]..function RunTheTest[52]..Test_reject_declaration[2]..Run_test_reject_declaration[1]..RunVimInTerminal[58]..TermWait[9]..<SNR>272_Exit_cb  line 3",vim
6,make: *** [Makefile:159: all] Error 2,warzone2100
2,CMake Error at src/plugins/CMakeLists.txt:116 (message):    Ruby not found,weechat
2,error: failed to run custom build command for `ring v0.16.20`, wezterm
1,"lj_arch.h:424:2: error: #error ""No target architecture defined""    424 | #error ""No target architecture defined""",wrk
5,c++: fatal error: Killed signal terminated program cc1plus,wyrmgus
4,pki_key.cpp:780:53: error: invalid conversion from 'const dsa_st*' to 'DSA*' {aka 'dsa_st*'} [-fpermissive],xca
4,parse.c:138:10: error: cast increases required alignment of target type [-Werror=cast-align]    138 |   return (XdgDirEntry *)g_array_free (array  FALSE);,xdg-user-dirs-gtk
4,regsmi.h:67:2: error: implicit declaration of function 'outb' [-Werror=implicit-function-declaration] regsmi.h:68:9: error: implicit declaration of function 'inb' [-Werror=implicit-function-declaration],xf86-video-siliconmotion
4,/home/abuild/rpmbuild/BUILD/xmrig-6.18.1/src/crypto/cn/asm/CryptonightR_template.S:6: Error: unknown pseudo-op: `.intel_syntax',xmrig
1,"lj_arch.h:472:2: error: #error ""No target architecture defined""      472 | #error ""No target architecture defined""",xplr
8,Error running (['dpkg-query'  '--showformat=${Version}'  '--show'  'xserver-xorg-video-dummy'] ) {'stdout': -1  'stderr': -1  'universal_newlines': True}: [Errno 2] No such file or directory: 'dpkg-query',xpra
6,make[1]: *** [CMakeFiles/Makefile2:263: CMakeFiles/stage3.dir/all] Error 2 make: *** [Makefile:139: all] Error 2,zig
2,ModuleNotFoundError: No module named 'javapackages',aalto-xml
4,hooklib.c:71:27: error: too many arguments to function 'libreport_get_dirsize_find_largest_dir',abrt
2,ModuleNotFoundError: No module named 'giscanner._giscanner',accountsservice
2,src/hashsum.c:85:3: error: 'GCRY_MD_SM3' undeclared here (not in a function); did you mean 'GCRY_MD_HD'?,aide
2,ModuleNotFoundError: No module named 'giscanner._giscanner',amtk
2,ModuleNotFoundError: No module named 'javapackages',ant-contrib
2,ModuleNotFoundError: No module named 'javapackages',antlr
10,UndeclaredThrowableException: InvocationTargetException: Plugin org.antlr:antlr3-maven-plugin:3.5 or one of its dependencies could not be resolved: Cannot access huaweicloud (https://mirrors.huaweicloud.com/repository/maven/) in offline mode and the artifact org.antlr:antlr3-maven-plugin:jar:3.5 has not been downloaded from it before.,antlr3
2,ModuleNotFoundError: No module named 'javapackages',aopalliance
2,ModuleNotFoundError: No module named 'javapackages',apache-commons-compress
2,ModuleNotFoundError: No module named 'javapackages',apache-commons-configuration
2,ModuleNotFoundError: No module named 'javapackages', apache-commons-digester
2,ModuleNotFoundError: No module named 'javapackages',apache-commons-exec
2,ModuleNotFoundError: No module named 'javapackages',apache-commons-jxpath
2,ModuleNotFoundError: No module named 'javapackages',apache-commons-lang3
2,ModuleNotFoundError: No module named 'javapackages',apache-commons-logging
2,ModuleNotFoundError: No module named 'javapackages',apache-commons-net
2,ModuleNotFoundError: No module named 'javapackages', apache-commons-parent
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project commons-pool2: There are test failures.,apache-commons-pool2
2,ModuleNotFoundError: No module named 'six',apache-commons-vfs
7,Job seems to be stuck here  killed. (after 28800 seconds of inactivity),apache-poi
2,[ERROR] /home/abuild/rpmbuild/BUILD/bnd-3.5.0.REL/biz.aQute.bndlib/src/aQute/bnd/testing/TestingLog.java:[11 28] cannot find symbol    symbol:   class Logger    location: package org.osgi.service.log,aqute-bnd
2,ModuleNotFoundError: No module named 'javapackages',args4j
2,ModuleNotFoundError: No module named 'javapackages',arquillian-core
2,ModuleNotFoundError: No module named 'javapackages',assertj-core
2,ModuleNotFoundError: No module named 'javapackages',atinject
2,ModuleNotFoundError: No module named 'giscanner._giscanner',atk
7,Job seems to be stuck here  killed. (after 28800 seconds of inactivity),atlas
5,unexpected fault address 0x220000000084a020 fatal error: fault [signal SIGSEGV: segmentation violation code=0x1 addr=0x220000000084a020 pc=0xf20f0],authz
3,make[2]: *** [Makefile:3065: test-suite.log] Error 1 make[1]: *** [Makefile:3173: check-TESTS] Error 2,automake
2,ModuleNotFoundError: No module named 'javapackages',aws-sdk-java
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,babel
7,Job seems to be stuck here  killed. (after 28800 seconds of inactivity),batik
2,ModuleNotFoundError: No module named 'javapackages', beust-jcommander
3,Test cases: 103 total  4 skipped  0 expected failures  2 broken  0 failed Total time: 1329.526s R:FAIL:status:1,bind
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,boom-boot
2,ModuleNotFoundError: No module named 'giscanner._giscanner',brasero
2,ModuleNotFoundError: No module named 'javapackages',bsf
2,ModuleNotFoundError: No module named 'javapackages',buildnumber-maven-plugin
2,ModuleNotFoundError: No module named 'javapackages',byte-buddy
7,"[timeout occurred during error reporting in step """"] after 30 s.",byteman
2,ModuleNotFoundError: No module named 'six',cal10n
2,ModuleNotFoundError: No module named 'six',cbi-plugins
2,ModuleNotFoundError: No module named 'javapackages',cdi-api
6,make: *** [Makefile:146: all] Error 2,ceph
3,Running test 001-keyiread... Files /tmp/runtestsa2apO4 and expected.out differ FAIL,certmonger
2,ModuleNotFoundError: No module named 'javapackages',cglib
2,ModuleNotFoundError: No module named 'javapackages',checkstyle
2,ModuleNotFoundError: No module named 'giscanner._giscanner',cheese
7,Job seems to be stuck here  killed. (after 28800 seconds of inactivity),chrony
2,ModuleNotFoundError: No module named 'yaml',cloud-init
2,ModuleNotFoundError: No module named 'giscanner._giscanner',clutter-gst3
2,ModuleNotFoundError: No module named 'giscanner._giscanner',clutter-gtk
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,cmake
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project CodeNarc: There are test failures.,codenarc
2,ModuleNotFoundError: No module named 'giscanner._giscanner',cogl
2,ModuleNotFoundError: No module named 'giscanner._giscanner',colord
4,container.if:13: Error: duplicate definition of container_runtime_domtrans(). Original definition on 13.,container-selinux
5,make: *** [Makefile:226: all] Segmentation fault (core dumped) ,crash
1,configure.ac:13: error: Autoconf version 2.71 or higher is required,cups
3,TESTFAIL: These test cases failed: 582,curl
2,ModuleNotFoundError: No module named 'javapackages',dain-snappy
1,file /usr/lib64/libasm-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,dconf
1,service/debugger/debugger.go:26:2: found packages native (proc.go) and your_operating_system_and_architecture_combination_is_not_supported_by_delve (support_sentinel.go) in /home/abuild/rpmbuild/BUILD/delve-1.6.0/pkg/proc/native,delve
7,Job seems to be stuck here  killed. (after 28800 seconds of inactivity),derby
2,ModuleNotFoundError: No module named 'giscanner._giscanner',devhelp
1,file /usr/lib64/libasm-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,dhcp
1,Makefile:77: *** unknown architecture  please fix Makefile.  Stop.,dietlibc
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,diffutils
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,djvulibre
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,dnf
2,ModuleNotFoundError: No module named 'javapackages',dom4j
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,dracut
1,unavailable-dwarf-piece-dw.S: Assembler messages: unavailable-dwarf-piece-dw.S:24: Error: non-constant .uleb128 is not supported,dwz
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project easymock: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test failed. ConcurrentModificationException,easymock
2,ModuleNotFoundError: No module named 'javapackages',ecj
2,ModuleNotFoundError: No module named 'six', eclipse-license
2,ModuleNotFoundError: No module named 'javapackages',eclipselink-persistence-api
2,ModuleNotFoundError: No module named 'javapackages',ed25519-java
1,cc1: error: unrecognized command-line option ‘-m32’ cc1: error: ‘-march=i586’: ISA string must begin with rv32 or rv64 cc1: error: unrecognized command-line option ‘-malign-double’,edk2
2,"meson.build:287:2: ERROR: Dependency ""luajit"" not found  tried pkgconfig and cmake",efl
2,ModuleNotFoundError: No module named 'javapackages',ehcache-sizeof-agent
1,At least Erlang/OTP 22.0 is required to build Elixir,elixir
2,ModuleNotFoundError: No module named 'giscanner._giscanner',eog
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21.,erlang-eflame
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21.,erlang-erlsyslog
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21.,erlang-erlydtl
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21.,erlang-getopt
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21.,erlang-gettext
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21.,erlang-hamcrest
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21.,erlang-lfe
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21.,erlang-meck
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21.,erlang-mustache
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21.,erlang-neotoma
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21., erlang-proper
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21.,erlang-protobuffs
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21.,erlang-rebar
1,beam/beam_load.c(1871): Error loading module getopt:    This BEAM file was compiled for a later version of the run-time system than 21.,erlang-sd_notify
2,ModuleNotFoundError: No module named 'giscanner._giscanner',esc
3, FAIL: TestPause (6.19s)      node_test.go:122: commits failed to converge! FAIL,etcd
2,ModuleNotFoundError: No module named 'giscanner._giscanner',evince
10,[ERROR]     Non-resolvable parent POM for org.atteo:evo-inflector:1.3: Could not transfer artifact org.atteo:parent:pom:1.19 from/to huaweicloud (https://mirrors.huaweicloud.com/repository/maven/): mirrors.huaweicloud.c,evo-inflector
2,ModuleNotFoundError: No module named 'giscanner._giscanner',evolution-data-server
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,exempi
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,extra-cmake-modules
2,configure: error: valgrind requested but <valgrind/memcheck.h> not found.,fabtests
3,make[3]: *** [Makefile:548: test-suite.log] Error 1 make[2]: *** [Makefile:656: check-TESTS] Error 2,fakeroot
2,ModuleNotFoundError: No module named 'giscanner._giscanner',farstream02
2,ModuleNotFoundError: No module named 'javapackages',fasterxml-oss-parent
7,Job seems to be stuck here  killed. (after 28800 seconds of inactivity),fastutil
2,ModuleNotFoundError: No module named 'javapackages',felix-bundlerepository
2,ModuleNotFoundError: No module named 'javapackages',felix-gogo-runtime
2,ModuleNotFoundError: No module named 'javapackages',felix-osgi-obr
2,ModuleNotFoundError: No module named 'javapackages',felix-parent
2,"error: Failed build dependencies: [ 2000s] 	mvn(org.osgi:osgi.cmpn) >= 7.0.0 is needed by felix-scr-2.1.16-1.oe1.noarch",felix-scr
2,ModuleNotFoundError: No module named 'six',felix-shell
2,ModuleNotFoundError: No module named 'javapackages',felix-utils
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,fftw
6,OverflowError: too many digits in integer,file-roller
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,firebird
4,KeyError: None,firefox
2,ModuleNotFoundError: No module named 'giscanner._giscanner',flatpack
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,flink
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,fltk
10,[FATAL] Non-resolvable parent POM for org.apache.flume:flume-parent:1.9.0: Could not transfer artifact org.apache:apache:pom:21 from/to huaweicloud (https://mirrors.huaweicloud.com/repository/maven/): mirrors.huaweicloud.com: Name or service not known and 'parent.relativePath' points at wrong local POM @ line 21  column 11,flume
4,14/43 folks:BluezBackend / individual-retrieval    FAIL             7.41s   killed by signal 5 SIGTRAP,folks
2,ModuleNotFoundError: No module named 'giscanner._giscanner',fonts-tweak-tool
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,foomatic-db
2,ModuleNotFoundError: No module named 'javapackages',fop
2,ModuleNotFoundError: No module named 'six',forbidden-apis
2,ModuleNotFoundError: No module named 'javapackages',forge-parent
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,freetds
2,ModuleNotFoundError: No module named 'javapackages',fusesource-pom
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gcab
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,GConf2
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,gcr
8,error: Directory not found: /home/abuild/rpmbuild/BUILDROOT/gdbus-codegen-glibmm-1.0.0-2.oe1.riscv64/usr/lib/python3.8/site-packages/gdbus_codegen.glibmm-2.99.0-py3.7.egg-info,gdbus-codegen-glibmm
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gdk-pixbuf2
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gdm
2,ModuleNotFoundError: No module named 'giscanner._giscanner',geoclue2
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,geocode-glib
8,g++_old: error: /usr/lib/gcc/riscv64-linux-gnu/9.3.1/crti.o: No such file or directory,geos
2,ModuleNotFoundError: No module named 'javapackages',geronimo-annotation
2,ModuleNotFoundError: No module named 'javapackages',geronimo-jms
2,ModuleNotFoundError: No module named 'javapackages',geronimo-jpa
2,ModuleNotFoundError: No module named 'javapackages',geronimo-jta
2,ModuleNotFoundError: No module named 'javapackages',geronimo-parent-poms
3,make[5]: *** [Makefile:2994: test-suite.log] Error 1 [22199s] make[4]: *** [Makefile:3102: check-TESTS] Error 2,gettext
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,git
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,glade
2,ModuleNotFoundError: No module named 'javapackages',glassfish-annotation-api
2,ModuleNotFoundError: No module named 'javapackages',glassfish-el
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project hk2-utils: There are test failures.,glassfish-hk2
2,ModuleNotFoundError: No module named 'six',glassfish-jax-rs-api
2,ModuleNotFoundError: No module named 'javapackages',glassfish-jsp-api
2,ModuleNotFoundError: No module named 'javapackages',glassfish-legal
2,ModuleNotFoundError: No module named 'javapackages',glassfish-master-pom
2,ModuleNotFoundError: No module named 'javapackages',glassfish-servlet-api
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project GMetrics: There are test failures.,gmetrics
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gmime30
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,gnome-abrt
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gnome-bluetooth
1,meson.build:47:0: ERROR: Invalid version of dependency  need 'folks' ['>=0.14'] found '0.11.4'.,gnome-contacts
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gnome-desktop3
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,gnome-initial-setup
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gnome-menus
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,gnome-online-accounts
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gnome-shell
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,gnome-themes-standard
2,ModuleNotFoundError: No module named 'encodings',gnu-free-fonts
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,gobject-introspection
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gom
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project gson: There are test failures.,google-gson
2,No module named 'nototools',google-noto-emoji-fonts
3,make[2]: *** [Makefile:6951: test-suite.log] Error 1 make[1]: *** [Makefile:7059: check-TESTS] Error 2,gperftools
2,ModuleNotFoundError: No module named 'javapackages',gradle
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,graphite2
2,ModuleNotFoundError: No module named 'giscanner._giscanner',grilo
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,groovy
6,collect2: error: ld returned 1 exit status make[2]: *** [Makefile:7656: grub-rpm-sort] Error 1,grub2
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,grubby
1,file /usr/lib64/libdw-0.185.so from install of elfutils-libs-0.185-3.oe1.riscv64 conflicts with file from package elfutils-0.185-5.oe1.riscv64,gsettings-desktop-schemas
3,FAIL: test,gsl
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gsound
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gssdp
2,ModuleNotFoundError: No module named 'encodings',gssntlmssp
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gstreamer1
2,ModuleNotFoundError: No module named 'encodings',gstreamer1-plugins-bad-free
2,Dependency gstreamer-1.0 found: NO found 1.16.2 but need: '>= 1.19.3',gstreamer1-plugins-good
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gstreamer-plugins-base
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gtk2
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gtk3
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gtksourceview3
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gtksourceview4
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gtk-vnc
2,ModuleNotFoundError: No module named 'javapackages',guava
2,ModuleNotFoundError: No module named 'javapackages',guava20
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gupnp-av
2,ModuleNotFoundError: No module named 'giscanner._giscanner',gupnp-dlna
9,[ERROR] [ERROR] Some problems were encountered while processing the POMs: [ERROR] Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.felix:maven-bundle-plugin:jar:2.5.0 ,Hadoop
9,[ERROR] [ERROR] Some problems were encountered while processing the POMs: [ERROR] Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.felix:maven-bundle-plugin:jar:2.5.0,hadoop-3.1
2,ModuleNotFoundError: No module named 'javapackages',hamcrest
2,ModuleNotFoundError: No module named 'giscanner._giscanner',harfbuzz
2,ModuleNotFoundError: No module named 'javapackages',hawtjni
9,[ERROR] [ERROR] Some problems were encountered while processing the POMs: [ 2464s] [ERROR] Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.felix:maven-bundle-plugin:jar:2.5.3,HdrHistogram
9,[ERROR] Failed to execute goal org.bsc.maven:maven-processor-plugin:2.2.4:process (process) on project hibernate-core: Error executing: error during compilation,hibernate
9,[ERROR] Failed to execute goal org.bsc.maven:maven-processor-plugin:2.2.4:process (process) on project hibernate-core: Error executing: error during compilation,hibernate4
2,ModuleNotFoundError: No module named 'javapackages',hibernate-jpa-2.0-api
10,[FATAL] Non-resolvable parent POM for org.apache.hive:hive:3.1.2: Could not transfer artifact org.apache:apache:pom:18 from/to huaweicloud (https://mirrors.huaweicloud.com/repository/maven/): mirrors.huaweicloud.com: Name or service not known and 'parent.relativePath' points at wrong local POM @ line 17  column 11,hive
10,[ERROR] Failed to execute goal on project hppc-template-processor: Could not resolve dependencies for project com.carrotsearch:hppc-template-processor:maven-plugin:0.7.1: Cannot access huaweicloud (https://mirrors.huaweicloud.com/repository/maven/) in offline mode and the artifact org.antlr:antlr-runtime:jar:3.5.2 has not been downloaded from it before.,hppc
2,ModuleNotFoundError: No module named 'javapackages',hsqldb
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project httpasyncclient: There are test failures.,httpcomponents-asyncclient
2,ModuleNotFoundError: No module named 'javapackages',httpcomponents-client
2,ModuleNotFoundError: No module named 'javapackages',httpcomponents-core
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,hunspell-hil
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,hunspell-ia
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,hunspell-is
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,hunspell-nr
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,hunspell-nso
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,hunspell-tl
8,error: #error no intrinsics file,hyperscan
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,hyphen-nl
8,fatal error: asm/types.h: No such file or directory,i40e
8,fatal error: asm/types.h: No such file or directory,iavf
2,ModuleNotFoundError: No module named 'giscanner._giscanner',ibus
2,ModuleNotFoundError: No module named 'gi',ibus-table
2,ModuleNotFoundError: No module named 'javapackages',icu4j
8,cp: cannot stat '/home/abuild/rpmbuild/SOURCES/patch.tar.gz': No such file or directory,isula-build
4,src/github.com/boltdb/bolt/freelist.go:207:7: undefined: maxAllocSize,iSulad-img
2,ModuleNotFoundError: No module named 'javapackages',jackson-bom
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project jackson-core: There are test failures.,jackson-core
2,ModuleNotFoundError: No module named 'javapackages',jackson-dataformats-binary
2,ModuleNotFoundError: No module named 'javapackages',jackson-parent
2,ModuleNotFoundError: No module named 'javapackages',jakarta-commons-httpclient
2,ModuleNotFoundError: No module named 'six',janino
2,ModuleNotFoundError: No module named 'javapackages',jansi
2,ModuleNotFoundError: No module named 'javapackages',jansi-native
2,ModuleNotFoundError: No module named 'javapackages',java_cup
2,ModuleNotFoundError: No module named 'javapackages',javacc-maven-plugin
8,Missing makefile.,java-service-wrapper
2,ModuleNotFoundError: No module named 'javapackages',javassist
10,[ERROR] Failed to execute goal on project jaxb2-basics: Could not resolve dependencies for project org.jvnet.jaxb2_commons:jaxb2-basics:jar:0.9.5: Cannot access huaweicloud,jaxb2-common-basics
2,ModuleNotFoundError: No module named 'javapackages',jaxen
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project jboss-classfilewriter: There are test failures., jboss-classfilewriter
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project jboss-dmr: There are test failures., jboss-dmr
2,ModuleNotFoundError: No module named 'javapackages',jboss-ejb-3.1-api
2,ModuleNotFoundError: No module named 'javapackages',jboss-parent
2,ModuleNotFoundError: No module named 'javapackages',jboss-remoting-jmx
2,ModuleNotFoundError: No module named 'javapackages',jboss-transaction-1.1-api
2,ModuleNotFoundError: No module named 'javapackages',jcifs
2,ModuleNotFoundError: No module named 'javapackages',jcip-annotations
2,ModuleNotFoundError: No module named 'javapackages',jcsp
2,ModuleNotFoundError: No module named 'javapackages',jdeparser2
2,ModuleNotFoundError: No module named 'javapackages',jdom
2,ModuleNotFoundError: No module named 'javapackages',jflex
2,ModuleNotFoundError: No module named 'javapackages',jgit
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project jmock: There are test failures.,jmock
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project jnr-enxio: There are test failures.,jnr-enxio
2,ModuleNotFoundError: No module named 'javapackages',jnr-ffi
2,ModuleNotFoundError: No module named 'javapackages',jnr-netdb
2,ModuleNotFoundError: No module named 'javapackages',jnr-posix
2,ModuleNotFoundError: No module named 'javapackages',jnr-x86asm
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project joda-time: There are test failures.,joda-time
4,[ERROR] /home/abuild/rpmbuild/BUILD/joni-joni-2.1.24/src/org/joni/Lexer.java:[30 30] cannot find symbol [ERROR]   symbol:   class EncodingError,joni
2,ModuleNotFoundError: No module named 'six',jopt-simple
4,line 16: It's not recommended to have unversioned Obsoletes: Obsoletes:      libjose line 33: It's not recommended to have unversioned Obsoletes: Obsoletes:      libjose-devel,jose
7,Job seems to be stuck here  killed. (after 28800 seconds of inactivity),jruby
2,ModuleNotFoundError: No module named 'javapackages',jsch
2,ModuleNotFoundError: No module named 'giscanner._giscanner',json-glib
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project json-path: There are test failures.,json-path
10,[ERROR] Failed to execute goal on project jsoup: Could not resolve dependencies for project org.jsoup:jsoup:jar:1.14.2: Cannot access huaweicloud,jsoup
10,[ERROR] Failed to execute goal on project tcl: Could not resolve dependencies for project org.jsr-305:tcl:jar:0.1-SNAPSHOT: Could not find artifact org.jsr-305:ri:jar:0.1-SNAPSHOT,jsr-305
2,ModuleNotFoundError: No module named 'six',junit5
2,ModuleNotFoundError: No module named 'javapackages',jvnet-parent
7,error(10):  internal error: org.antlr.tool.Grammar.createLookaheadDFA(Grammar.java:1279): could not even do k=1 for decision 130; reason: timed out,jython
4,./agent.go:733:17: undefined: initRootBusPath,kata-containers
2,ModuleNotFoundError: No module named 'javapackages',kohsuke-pom
1,Makefile:30: *** Unsupported architecture riscv64  check https://github.com/dynup/kpatch/#supported-architectures.  Stop.,kpatch
7,Timeout:            25  ,ksh
10,[ERROR] Failed to execute goal on project language-detector: Could not resolve dependencies for project com.optimaize.languagedetector:language-detector:jar:0.6: Cannot access huaweicloud,language-detector
3,make[5]: *** [Makefile:966: test-suite.log] Error 1 make[4]: *** [Makefile:1074: check-TESTS] Error 2,lasso
7,Job seems to be stuck here  killed. (after 28800 seconds of inactivity), leveldb-java
2,ModuleNotFoundError: No module named 'javapackages',leveldbjni
4,error: 'SYS_eventfd' undeclared (first use in this function); did you mean 'SYS_eventfd2'?,libaio
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libappindicator
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libappstream-glib
4,error: 'struct user_regs_struct' declared inside parameter list will not be visible outside of this definition or declaration,libcareplus
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,libcomps
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libdazzle
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libdbusmenu
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libdmapsharing
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libeasyfc
2,generic' is not a recognized processor for this target (ignoring processor),libepoxy
3,1/325 TESTS FAILED. (27 skipped),libevent
2,ModuleNotFoundError: No module named 'SCons',libffado
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libgdata
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libgdl
8,error: File not found: /home/abuild/rpmbuild/BUILDROOT/libgexiv2-0.12.1-1.oe1.riscv64/usr/lib64/python3.8/site-packages/gi/overrides/GExiv2.py,libgexiv2
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libgit2-glib
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libgnomekbd
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libgnome-keyring
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libgovirt
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libgsf
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libgtop2
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libgudev
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libgusb
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libgweather
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libgxps
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libhandy
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libical
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,liblognorm
8,libmicrohttpd-tutorial.texi:115: @include: could not find chapters/websocket.inc, libmicrohttpd
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libmodulemd
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libmypaint
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libnice
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libnma
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libnotify
3,make[2]: *** [Makefile:519: check-TESTS] Error 1 make[1]: *** [Makefile:802: check-am] Error 2,liboauth
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libosinfo
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libpeas
3,make[3]: *** [Makefile:792: test-suite.log] Error 1 make[2]: *** [Makefile:900: check-TESTS] Error 2,libraqm
2,ModuleNotFoundError: No module named 'giscanner._giscanner', librsvg2
8,fatal error: valgrind/valgrind.h: No such file or directory,libsecret
2,ModuleNotFoundError: No module named 'Scons,libserf
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libsoup
2,configure: error: 'libgeos_c' (>= v.3.7.0) is required but it doesn't seem to be installed on this system. You may need to try re-running configure with a --disable-geos370 parameter.,libspatialite
2,configure: error: failed to find required module pywbem,libstoragemgmt
2,ERROR: System library talloc of version 2.3.2 not found  and bundling disabled,libtevent
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libtimezonemap
2,ModuleNotFoundError: No module named 'giscanner._giscanner', libvirt-glib
4,error No architecture specific memory barrier definitions found!,libvma
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libwnck
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libwnck3
2,configure: error: Package requirements (xproto fixesproto >= 6.0 xextproto x11 >= 1.6) were not met:,libXfixes
2,"	configure: error: Package requirements (xproto >= 7.0.13 x11 >= 1.6 xextproto >= 7.0.3 xext >= 1.0.99.1 inputproto >= 2.3.99.1) were not met:",libXi
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libxklavier
2,ModuleNotFoundError: No module named 'giscanner._giscanner',libxmlb
6,/usr/lib/rpm/brp-digest-list: line 32: gen_digest_lists: command not found,libzapojit
4,/usr/include/c++/10.3.1/bits/atomic_base.h:443: undefined reference to `__atomic_exchange_1',lldb
2,ModuleNotFoundError: No module named 'six',log4j12
2,ModuleNotFoundError: No module named 'encodings',lohit-assamese-fonts
2,ModuleNotFoundError: No module named 'encodings',lohit-bengali-fonts
2,ModuleNotFoundError: No module named 'encodings',lohit-devanagari-fonts
2,ModuleNotFoundError: No module named 'encodings',lohit-gujarati-fonts
2,ModuleNotFoundError: No module named 'encodings',lohit-gurmukhi-fonts
2,ModuleNotFoundError: No module named 'encodings',lohit-malayalam-fonts
2,ModuleNotFoundError: No module named 'encodings',lohit-marathi-fonts
2,ModuleNotFoundError: No module named 'encodings',lohit-nepali-fonts
2,ModuleNotFoundError: No module named 'encodings',lohit-odia-fonts
2,ModuleNotFoundError: No module named 'encodings',lohit-tamil-fonts
8,/bin/sh: line 21: cd: riscv64: No such file or directory,ltrace
2,ModuleNotFoundError: No module named 'javapackages',lucene
3,1 Test in 1 Category Failed,make
9,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project maven-archiver: Compilation failure,maven-archiver
2,ModuleNotFoundError: No module named 'javapackages',maven-artifact-resolver
2,ModuleNotFoundError: No module named 'javapackages',maven-artifact-transfer
9,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project maven-assembly-plugin: Compilation failure,maven-assembly-plugin
2,ModuleNotFoundError: No module named 'javapackages',maven-clean-plugin
2,ModuleNotFoundError: No module named 'javapackages',maven-common-artifact-filters
2,ModuleNotFoundError: No module named 'javapackages',maven-compiler-plugin
2,ModuleNotFoundError: No module named 'javapackages',maven-dependency-plugin
2,ModuleNotFoundError: No module named 'javapackages',maven-dependency-tree
2,ModuleNotFoundError: No module named 'javapackages',maven-doxia
2,ModuleNotFoundError: No module named 'javapackages',maven-doxia-sitetools
2,ModuleNotFoundError: No module named 'javapackages',maven-enforcer
2,ModuleNotFoundError: No module named 'javapackages',maven-install-plugin
2,ModuleNotFoundError: No module named 'javapackages',maven-invoker-plugin
2,ModuleNotFoundError: No module named 'javapackages',maven-javadoc-plugin
2,ModuleNotFoundError: No module named 'javapackages',maven-parent
2,ModuleNotFoundError: No module named 'javapackages',maven-plugin-build-helper
2,ModuleNotFoundError: No module named 'javapackages',maven-plugin-bundle
2,ModuleNotFoundError: No module named 'javapackages',maven-plugins-pom
2,ModuleNotFoundError: No module named 'javapackages',maven-plugin-testing
2,ModuleNotFoundError: No module named 'javapackages',maven-remote-resources-plugin
2,ModuleNotFoundError: No module named 'javapackages',maven-reporting-api
2,ModuleNotFoundError: No module named 'javapackages',maven-reporting-impl
2,ModuleNotFoundError: No module named 'javapackages',maven-resolver
2,ModuleNotFoundError: No module named 'javapackages',maven-resources-plugin
2,ModuleNotFoundError: No module named 'javapackages',maven-scm
2,ModuleNotFoundError: No module named 'javapackages',maven-shade-plugin
2,ModuleNotFoundError: No module named 'javapackages',maven-shared
2,ModuleNotFoundError: No module named 'javapackages',maven-shared-utils
2,ModuleNotFoundError: No module named 'javapackages',maven-surefire
1,Error: unsupported machine: riscv64.,memleax
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project metadata-extractor: There are test failures.,metadata-extractor2
2,ModuleNotFoundError: No module named 'javapackages',minlog
7,Error: timeout of 50ms exceeded. Ensure the done() callback is being called in this test.,mocha
2,ModuleNotFoundError: No module named 'javapackages',mockito
8,h2_conn_io.c:27:10: fatal error: http_ssl.h: No such file or directory,mod_http2
2,configure: error: Couldn't find libqmi-glib >= 1.26.0. Install it  or otherwise configure using --without-qmi to disable QMI support.,ModemManager
2,ModuleNotFoundError: No module named 'javapackages',mongo-java-driver
2,configure: error: cannot guess build type; you must specify one,motif
1,ERROR: Unknown CPU type: riscv64,mozjs52
2,ModuleNotFoundError: No module named 'javapackages',munge-maven-plugin
6,meson.build:285:2: ERROR: Automatic wrap-based subproject downloading is disabled,mutter
9,[ERROR] No plugin found for prefix 'install' in the current project and in the plugin groups [org.apache.maven.plugins  org.codehaus.mojo] available from the repositories,mybatis
2,ModuleNotFoundError: No module named 'javapackages',native-platform
2,ModuleNotFoundError: No module named 'javapackages',nekohtml
1,[ERROR] unknown os.arch: riscv64,netty
2,ModuleNotFoundError: No module named 'javapackages',netty3
2,ModuleNotFoundError: No module named 'javapackages',netty-tcnative
2,configure: error: introspection enabled but can't be used,NetworkManager
1,configure: error: Package requirements (libnftnl >= 1.2.0) were not met: Package dependency requirement 'libnftnl >= 1.2.0' could not be satisfied. Package 'libnftnl' has version '1.1.8'  required version is '>= 1.2.0',nftables
3,tests 19 pass  18 fail  1,nodejs-glob
4,events - events...[31mFatal error: (node:1146476) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.,nodejs-grunt-contrib-watch
2,"gyp ERR! configure error  gyp ERR! stack Error: Can't find Python executable ""python""  you can set the PYTHON env variable.",nodejs-iconv
8,find: 'debug': No such file or directory,nodejs-is-regex
8,find: 'debug': No such file or directory,nodejs-is-symbol
3,8[31m Failed[39m  393 passed - Test Sync math/strict-legacy/css: [32mOK[39m,nodejs-less
3,tests 1 fail  1,nodejs-minimist
3,/var/tmp/rpm-tmp.qHJJr6: line 33: 149216 Aborted                 (core dumped) /usr/lib/node_modules/mocha/bin/mocha --recursive test,nodejs-mock-fs
7,Error: timeout of 200ms exceeded,nodejs-promise
7,Error: timeout of 2000ms exceeded,nodejs-raw-body
4,"TypeError [ERR_INVALID_ARG_TYPE]: The ""data"" argument must be of type string or an instance of Buffer  TypedArray  or DataView. Received an instance of SourceMapGenerator",nodejs-source-map-support
7,timeout test,nodejs-tap
3,tests 36 pass  34 fail  2,nodejs-traverse
4,/usr/bin/ld: ./.libs/libnuma.so: undefined reference to `__atomic_fetch_and_1',numactl
2,ModuleNotFoundError: No module named 'javapackages',objectweb-asm
2,ModuleNotFoundError: No module named 'javapackages',objectweb-asm3
2,ModuleNotFoundError: No module named 'javapackages',objectweb-pom
1,Ruby  (< 3.2.dev  >= 2.6)  which is required by gem 'rails (~> 5.2)'  is not available in the local ruby installation,obs-bundled-gems
1,Unable to find a spec satisfying nokogiri (>= 0) in the set. Perhaps the lockfile is corrupted? Found nokogiri (1.13.3-x86_64-linux)  nokogiri  (1.13.3-x86_64-linux)  nokogiri (1.13.3-x86_64-linux)  nokogiri  (1.13.3-x86_64-linux) that did not match the current platform.,obs-server
8,error: File not found: /home/abuild/rpmbuild/BUILDROOT/oemaker-2.0.3-13.oe1.riscv64/etc/isocut/anaconda-ks.cfg,oemaker
2,ModuleNotFoundError: No module named 'encodings',openjdk-11
2,configure: WARNING: valgrind.h not found configure: WARNING: Cannot compile this component configure: error: Cannot continue,openmpi
2,ModuleNotFoundError: No module named 'javapackages',opentest4j
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,openvswitch
3,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project openwebbeans-impl: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test failed. ConcurrentModificationException,openwebbeans
2,configure: error: Could not find python module: gi,orca
2,ModuleNotFoundError: No module named 'javapackages',osgi-annotation
2,ModuleNotFoundError: No module named 'javapackages',osgi-compendium
2,ModuleNotFoundError: No module named 'javapackages',osgi-core
2,ModuleNotFoundError: No module named 'giscanner._giscanner',ostree
6,help2man: can't get `--help' info from /home/abuild/rpmbuild/BUILD/pacemaker-Pacemaker-2.0.5/tools/crm_shadow,pacemaker
2,ModuleNotFoundError: No module named 'giscanner._giscanner',PackageKit
2,ModuleNotFoundError: No module named 'giscanner._giscanner',pango
2,configure: error: cannot guess build type; you must specify one,passenger
3,[ERROR] Tests run: 5  Failures: 0  Errors: 1  Skipped: 0  Time elapsed: 3 226.333 s <<< FAILURE! - in org.apache.pdfbox.encryption.TestSymmetricKeyEncryption,pdfbox
1,Alien::Build version 2.37 required--this is only version 2.28 at /usr/share/perl5/vendor_perl/Alien/Build.pm line 319.,perl-Alien-Libxml2
3,Failed 14/29 test programs. 22/506 subtests failed.,perl-bignum
3,Failed 2/18 test programs. 1958/9107 subtests failed.,perl-Math-BigRat
3,Failed 11/11 test programs. 2/2 subtests failed.,perl-PathTools
4,"error: missing binary operator before token ""("" error: 'PerlInterpreter' {aka 'struct interpreter'} has no member named 'Tstack_base'; did you mean 'Istack_base'?",perl-threads
4,"error: missing binary operator before token ""(""",perl-threads-shared
4,"error: missing binary operator before token ""(""",perl-Time-HiRes
4,"error: missing binary operator before token ""(""",perl-Unicode-Normalize
2,ModuleNotFoundError: No module named 'flask_limiter',pkgship
2,ModuleNotFoundError: No module named 'javapackages',plexus-ant-factory
9,ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project plexus-archiver: Compilation failure,plexus-archiver
2,ModuleNotFoundError: No module named 'javapackages',plexus-bsh-factory
10,[ERROR] [ERROR] Some problems were encountered while processing the POMs: [FATAL] Non-resolvable parent POM for org.sonatype.plexus:plexus-build-api:0.0.7: Could not transfer artifact org.sonatype.spice:spice-parent:pom:15 from/to huaweicloud,plexus-build-api
2,ModuleNotFoundError: No module named 'javapackages',plexus-cipher
2,ModuleNotFoundError: No module named 'javapackages',plexus-classworlds
2,ModuleNotFoundError: No module named 'javapackages',plexus-cli
2,ModuleNotFoundError: No module named 'javapackages',plexus-compiler
2,ModuleNotFoundError: No module named 'javapackages',plexus-i18n
2,ModuleNotFoundError: No module named 'javapackages',plexus-interactivity
9,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project plexus-io: Compilation failure,plexus-io
2,ModuleNotFoundError: No module named 'javapackages',plexus-pom
2,ModuleNotFoundError: No module named 'javapackages',plexus-resources
2,ModuleNotFoundError: No module named 'javapackages',plexus-velocity
4,_build/src/github.com/containers/libpod/vendor/github.com/boltdb/bolt/freelist.go:204:17: undefined: maxAllocSize,podman
2,ModuleNotFoundError: No module named 'six',polyglot
2,ModuleNotFoundError: No module named 'giscanner._giscanner',poppler
9,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project postgresql: Compilation failure,postgresql-jdbc
9,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project protobuf-javalite: Compilation failure,protobuf
1,Package dependency requirement 'protobuf >= 2.6.0' could not be satisfied. Package 'protobuf' has version '2.5.0'  required version is '>= 2.6.0',protobuf-c
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,py3c
3,444 failed  699 passed  44 skipped  220 deselected  7 warnings in 2403.54 seconds ,pylint
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,pyOpenSSL
2,ModuleNotFoundError: No module named 'sipconfig',PyQt4
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,pyScss
1,distutils.errors.DistutilsError: Command '['/usr/bin/python3'  '-m'  'pip'  '--disable-pip-version-check'  'wheel'  '--no-deps'  '-w'  '/tmp/tmpqxseg00m'  '--quiet'  'setuptools-scm>=3.4']',pytest
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,python-atomicwrites
2,ModuleNotFoundError: No module named 'pytz',python-breathe
3,13 skipped  11 deselected  28 warnings  6 error in 839.31 seconds,python-cryptography
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,python-entrypoints
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,python-execnet
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babe,python-filelock
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babe,python-funcsigs
4,error: ‘EVBACKEND_LINUXAIO’ undeclared (first use in this function) error: ‘EVBACKEND_IOURING’ undeclared (first use in this function); did you mean ‘EVBACKEND_PORT’?,python-gevent
2,ModuleNotFoundError: No module named 'tornado',python-httpretty
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,python-hypothesis
1,distutils.errors.DistutilsError: Command '['/usr/bin/python3'  '-m'  'pip'  '--disable-pip-version-check'  'wheel'  '--no-deps'  '-w'  '/tmp/tmp0lyyfq1n'  '--quiet'  'setuptools_scm[toml]>=3.4.1']' returned non-zero exit status 1.,python-importlib-resources
1,distutils.errors.DistutilsError: Command '['/usr/bin/python3'  '-m'  'pip'  '--disable-pip-version-check'  'wheel'  '--no-deps'  '-w'  '/tmp/tmp7j5_o2u2'  '--quiet'  'setuptools_scm[toml]>=3.4.1']' returned non-zero exit status 1.,python-jaraco-functools
7,Job seems to be stuck here  killed. (after 28800 seconds of inactivity),python-joblib
4,AttributeError: 'NoneType' object has no attribute 'split',python-jsonpatch
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,python-netaddr
2,ModuleNotFoundError: No module named 'pytz',python-nss
1,RuntimeError: Cannot cythonize with old Cython version (0.29.14 installed  needs 0.29.21),python-pandas
2,pkg_resources.DistributionNotFound: The 'PasteDeploy' distribution was not found and is required by the application,python-paste-deploy
3,FAILED Tests/oss-fuzz/test_fuzzers.py - AttributeError: 'Version' object has …,python-pillow
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,python-py
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,python-pyasn1
2,ModuleNotFoundError: No module named 'pytz',python-pybeam
1,distutils.errors.DistutilsError: Command '['/usr/bin/python3'  '-m'  'pip'  '--disable-pip-version-check'  'wheel'  '--no-deps'  '-w'  '/tmp/tmphjcf8wjt'  '--quiet'  'pytz>=2015.7']' returned non-zero exit status 1.,python-pygments
2,ModuleNotFoundError: No module named 'Image',python-qrcode
1,Error: This version of PyQt5 requires sip 4.19.23 or later.,python-qt5
2,ImportError: scipy is not installed.,python-scikit-learn
2,ModuleNotFoundError: No module named 'pytz',python-sphinx
1,distutils.errors.DistutilsError: Command '['/usr/bin/python3'  '-m'  'pip'  '--disable-pip-version-check'  'wheel'  '--no-deps'  '-w'  '/tmp/tmp_c1huvz4'  '--quiet'  'setuptools_scm[toml]>=3.4']' returned non-zero exit status 1.,python-tqdm
2,ModuleNotFoundError: No module named 'tornado',python-urllib3
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,python-webencodings
2,ModuleNotFoundError: No module named 'werkzeug.middleware',python-werkzeug
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,python-wrapt
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,python-zope-event
2,ERROR: Could not find a version that satisfies the requirement coverage>=5.0.3 (from versions: none),python-zope-interface
2,RuntimeError: Missing build dependency: Unable to `import yaml`.,pytorch
2,ModuleNotFoundError: No module named 'javapackages',qdox
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,qemu
3,ESTS COMPLETE.  Summary: Total tests: 2133 Passes: 2129 Failures: 1 Unexpected Passes: 0 Expected Failures: 3, qpdf
2,pkg_resources.DistributionNotFound: The 'pytz>=2015.7' distribution was not found and is required by babel,qpid-proton
4,UnboundLocalError: local variable 'QtCore' referenced before assignment,qscintilla
4,qdeclarativepositionsource.cpp:283:49: error: 'errorOccurred' is not a member of 'QAbstractSocket',qt5-qtlocation
4,debugging/qscriptdebuggerconsole.cpp:407:48: error: 'SkipEmptyParts' is not a member of 'Qt',qt5-qtscript
4,WARNING: /home/abuild/rpmbuild/BUILD/webkit-qtwebkit-23/Tools/qmake/mkspecs/features/use_all_in_one_files.prf:15: Unmatched parentheses are deprecated.,qtwebkit
2,ModuleNotFoundError: No module named 'six',reflections
2,ModuleNotFoundError: No module named 'giscanner._giscanner',rest
2,ModuleNotFoundError: No module named 'javapackages',hino
2,ModuleNotFoundError: No module named 'giscanner._giscanner',rpm-ostree
3,388 scenarios ([31m7 failed[0m  [36m4 skipped[0m  [32m377 passed[0m) 1832 steps ([31m7 failed[0m  [36m17 skipped[0m  [32m1808 passed[0m) 61m12.881s,rubygem-aruba
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,rubygem-atomic
4,NoMethodError: undefined method `source_location' for #<Binding:0x0000002ac6508d18>,rubygem-bindex
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,rubygem-byebug
3,rspec ./spec/builtin_contracts_spec.rb:440 # Contracts: StrictHash: when given an input with missing keys raises an error, rubygem-contracts
3,cucumber features/docs/defining_steps/nested_steps.feature:111 # Scenario: Backtrace doesn't skip nested steps,rubygem-cucumber
7,cucumber features/timeouts.feature:30 # Scenario: Invoke a step definition that takes longer than its timeout,rubygem-cucumber-wire
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,rubygem-fattr
4,ruby: invalid option -:  (-h will show valid options) (RuntimeError),rubygem-flexmock
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,rubygem-httpclient
3,TestFiles#test_gfm_header_ids_to_html [/home/abuild/rpmbuild/BUILD/kramdown-parser-gfm-1.1.0/usr/share/gems/gems/kramdown-parser-gfm-1.1.0/test/test_files.rb:32]:,rubygem-kramdown-parser-gfm
1,An error occurred while loading ./spec/sinatra_spec.rb. Failure/Error: require 'ruby2_keywords',rubygem-mustermann
6,tee: /dev/stderr: Permission denied,rubygem-prawn
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,rubygem-prawn-table
4,/home/abuild/rpmbuild/BUILD/rails-html-sanitizer-1.4.2/usr/share/gems/gems/rails-html-sanitizer-1.4.2/test/sanitizer_test.rb:184:in `<class:SanitizersTest>': uninitialized constant Loofah::HTML5::SafeList (NameError),rubygem-rails-html-sanitizer
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,rubygem-rake-compiler
3,594 tests  5247 assertions  1 failure,rubygem-redis
8,rpmbuild: error while loading shared libraries: libelf.so.1: cannot open shared object file: No such file or directory,rubygem-session
3,1 tests  0 assertions  0 failures  1 errors,rubygem-shoulda
4,TZInfo::DataSources::TCZoneinfoDataSource#test_timezone_identifiers_excludes_those_that_cannot_be_utf8_encoded: NoMethodError: undefined method `call' for nil:NilClass,rubygem-tzinfo
2,ERROR: Python module pytdb of version 1.4.3 not found  and bundling disabled,samba
7,Job seems to be stuck here  killed. (after 28800 seconds of inactivity),sbt
7,Job seems to be stuck here  killed. (after 28800 seconds of inactivity),scala
2,CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message): Could NOT find PY_yaml (missing: PY_YAML),scap-security-guide
2,ModuleNotFoundError: No module named 'selinux',setroubleshoot
2,ModuleNotFoundError: No module named 'javapackages', shrinkwrap
4,Error: child killed by signal 6 (Aborted),simde
2,ModuleNotFoundError: No module named 'javapackages', sisu
2,ModuleNotFoundError: No module named 'six',sisu-mojos
2,ModuleNotFoundError: No module named 'javapackages',slf4j
2,ModuleNotFoundError: No module named 'giscanner._giscanner',snapd-glib
2,ModuleNotFoundError: No module named 'javapackages',sonatype-oss-parent
2,ModuleNotFoundError: No module named 'six',spatial4j
2,ModuleNotFoundError: No module named 'giscanner._giscanner',spice-gtk
2,ModuleNotFoundError: No module named 'javapackages',spice-parent
2,ModuleNotFoundError: No module named 'six',spymemcached
7,[java] error(10):  internal error: org.antlr.tool.Grammar.createLookaheadDFA(Grammar.java:1279): could not even do k=1 for decision 26; reason: timed out (>1000ms),sqljet
4,error: 'LIBECAP_VERSION' was not declared in this scope; did you mean 'SSL_SECOP_VERSION'?,squid
3,make[4]: *** [Makefile:40491: test-suite.log] Error 1 make[3]: *** [Makefile:40599: check-TESTS] Error 2,sssd
2,ModuleNotFoundError: No module named 'javapackages',stax2-api
10,[ERROR] [ERROR] Some problems were encountered while processing the POMs: [FATAL] Non-resolvable parent POM for org.jvnet.staxex:stax-ex:1.8: Could not transfer artifact net.java:jvnet-parent:pom:5 from/to huaweicloud,stax-ex
1,configure.ac:20: error: Autoconf version 2.70 or higher is required configure.ac:20: the top level,sudo
3,make[3]: *** [Makefile:698: test-suite.log] Error 1 make[2]: *** [Makefile:806: check-TESTS] Error 2,swtpm
2,configure: error: Package requirements (luajit) were not met: Package 'luajit'  required by 'virtual:world'  not found,sysbench
4,vendor/github.com/opencontainers/runc/libcontainer/init_linux.go:271:12: undefined: system.Setuid,syscontainer-tools
2,ModuleNotFoundError: No module named 'giscanner._giscanner',telepathy-glib
2,ModuleNotFoundError: No module named 'giscanner._giscanner',telepathy-logger
8,tar: /home/abuild/rpmbuild/SOURCES/external-riscv64.tar.bz2: Cannot open: No such file or directory,tensorflow
2,ModuleNotFoundError: No module named 'javapackages',testing
2,configure: error: some requested system libraries failed,texlive-base
2,configure: error: failed to find required module fontforge,thai-scalable-fonts
6,/home/abuild/rpmbuild/BUILD/pegasus/mak/config.mak:336: *** PEGASUS_PLATFORM environment variable must be set to one of the following:,tog-pegasus
2,ModuleNotFoundError: No module named 'giscanner._giscanner', totem
2,ModuleNotFoundError: No module named 'giscanner._giscanner',totem-pl-parser
2,ModuleNotFoundError: No module named 'giscanner._giscanner',tracker
9,[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project tycho-p2-extras-plugin: Compilation failure,tycho-extras
1,configure: error: Package requirements (blockdev >= 2.25) were not met: Package dependency requirement 'blockdev >= 2.25' could not be satisfied. Package 'blockdev' has version '2.24'  required version is '>= 2.25',udisks2
2,ModuleNotFoundError: No module named 'giscanner._giscanner',upower
4,error: array bound is not an integer constant before ']' token,usbguard
3,1 tests of 213 FAILED,util-linux
2,configure: error: Package requirements (libpcre2-8) were not met: Package 'libpcre2-8'  required by 'virtual:world'  not found,varnish
6,error: %prein(fipscheck-1.5.0-7.oe1.riscv64) scriptlet failed  signal 6 error: fipscheck-1.5.0-7.oe1.riscv64: install failed,vcftools
1,meson.build:77:0: ERROR: Invalid version of dependency  need 'epoxy' ['>= 1.5.4'] found '1.5.3'.,virglrenderer
3,make[3]: *** [Makefile:741: test-suite.log] Error 1 make[2]: *** [Makefile:849: check-TESTS] Error 2,volume_key
2,ModuleNotFoundError: No module named 'giscanner._giscanner',vte
2,ModuleNotFoundError: No module named 'javapackages', weld-api
2,ModuleNotFoundError: No module named 'six',weld-core
2,ModuleNotFoundError: No module named 'six',weld-parent
7,Job seems to be stuck here  killed. (after 28800 seconds of inactivity),wildfly-core
2,ModuleNotFoundError: No module named 'javapackages',woodstox-core
2,ModuleNotFoundError: No module named 'javapackages',xalan-j2
2,ModuleNotFoundError: No module named 'javapackages',xbean
2,ModuleNotFoundError: No module named 'javapackages',xerces-j2
2,ModuleNotFoundError: No module named 'javapackages',xml-commons-apis
2,ModuleNotFoundError: No module named 'javapackages',xml-commons-resolver
2,ModuleNotFoundError: No module named 'javapackages',xmlgraphics-commons
2,ModuleNotFoundError: No module named 'javapackages',xmvn
2,ModuleNotFoundError: No module named 'javapackages',xnio
1,Package dependency requirement 'inputproto >= 2.3.99.1' could not be satisfied. Package 'inputproto' has version '2.3.2'  required version is '>= 2.3.99.1',xorg-x11-drv-libinput
4,error: two or more data types in declaration specifiers,xorg-x11-drv-qxl
2,ModuleNotFoundError: No module named 'javapackages',xz-java
10,[ERROR] [ERROR] Some problems were encountered while processing the POMs: [FATAL] Non-resolvable parent POM for org.apache.zookeeper:parent:3.6.2: Could not transfer artifact org.apache:apache:pom:23 from/to huaweicloud,zookeeper
