label,log,package
1,g++: error: '-march=pentium3': ISA string must begin with rv32 or rv64 make[1]: *** [mocks_real.make:99: obj/mocks_real_Release/mocks_real.o] Error 1 make: *** [Makefile:159: mocks_real] Error 2,0ad
1,"error: #error ""No support for this architecture (yet)"" Makefile:269: *** Unsupported target architecture.",ageisub
5,[  924.609180][T16993] Out of memory: Killed process 16993 (pandoc) total-vm:1079089668kB  anon-rss:2877596kB  file-rss:0kB  shmem-rss:0kB  UID:399 pgtables:9740kB oom_score_adj:0 ,amsynth
5,#warning You are compiling libardour on a platform for which ardour/cycles.h needs work Build failed -> task in 'libardour' failed with exit status 1 (run with -v to display more information),ardour
2,error: failed to run custom build command for `ring v0.16.20` ,atuin
3,AUBIO-TESTS ERROR: not enough arguments  running tests AUBIO ERROR: source_avcodec: Aborted opening null path AUBIO ERROR: source_avcodec: Failed opening  (No such file or directory),aubio
2,CMake Error at cmake-proxies/cmake-modules/Findvst3sdk.cmake:56 (message): Failed to build VST3SDK Configuring incomplete  errors occurred!,audacity
3,"The following tests FAILED: 	  1 - bear::func_test (Timeout) Errors while running Ctest",Bear
2,/bin/sh: line 1: git: command not found make: *** [Makefile:181: obj/filter/tree_test.ok] Error 139,bird
1,"meson.build:90:1: ERROR: Problem encountered: Architecture ""riscv64"" is not supported.",boxfort
5,AssertionError: MemoryError not raised,breezy
6,lto-wrapper: fatal error: make returned 2 exit status ,bulk_extractor
5,[  111.621611][ T4183] Out of memory: Killed process 4183 (qemu-riscv64) total-vm:1078697528kB  anon-rss:3486616kB  file-rss:0kB  shmem-rss:0kB  UID:399 pgtables:9108kB,bup
3,deviation in file beamfsh1.dat line: 103 reference value: -5.943977e-09 value: -3.410154e-10               absolute error: 5.602962e-09               largest value within same block: 1.276463e-07               relative error w.r.t. largest value within same block: 4.389443 %,ccx
6,lto-wrapper: fatal error: make returned 2 exit status,clanlib
2,Module build failed (from ./node_modules/babel-loader/lib/index.js)： NonErrorEmittedError: (Emitted value instead of an instance of Error) [object Object] webpack 5.74.0 compiled with 15 errors in 219686 ms,cockpit
2,Module build failed (from ./node_modules/babel-loader/lib/index.js): NonErrorEmittedError: (Emitted value instead of an instance of Error) [object Object] webpack compiled with 8 errors,cockpit-d-installer
8,error: File not found: /home/abuild/rpmbuild/BUILDROOT/collectd-5.9.0.130.g2f3c9e-1.3.riscv64/usr/lib64/collectd/nut.so  error: File not found: /home/abuild/rpmbuild/BUILDROOT/collectd-5.9.0.130.g2f3c9e-1.3.riscv64/usr/lib64/collectd/nut.la,collectd
4,/usr/lib64/gcc/riscv64-suse-linux/9/../../../../riscv64-suse-linux/bin/ld: /tmp/cc7rEUJG.ltrans5.ltrans.o: in function `.L0 ': /home/abuild/rpmbuild/BUILD/coturn-4.6.1/src/apps/common/ns_turn_utils.c:606: undefined reference to `FIPS_mode',coturn
3,"The following tests FAILED: 	 13 - TestCondition (Failed) Errors while running Ctest",cppcheck
1,./dapl/udapl/linux/dapl_osd.h:55:2: error: #error UNDEFINED ARCH   #error UNDEFINED ARCH,dapl
1,./dapl/udapl/linux/dapl_osd.h:55:2: error: #error UNDEFINED ARCH   #error UNDEFINED ARCH,dapl-debug
6,service/debugger/debugger.go:32:2: found packages native (dump_linux.go) and your_linux_architecture_is_not_supported_by_delve (support_sentinel_linux.go) in /home/abuild/rpmbuild/BUILD/delve-1.20.0/pkg/proc/native,delve
4,dh.cc:40:23: error: 'get_dh2048' was not declared in this scope,drops
8,cc1: fatal error: renesas/*.dts: No such file or directory,dtb-riscv64
2,ERROR in ./node_modules/matrix-react-sdk/res/img/feather-customised/warning-triangle.svg      Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):      NonErrorEmittedError: (Emitted value instead of an instance of Error) [object Object],element-web
3,ERROR: One or more eunit tests failed. ERROR: eunit failed while processing /home/abuild/rpmbuild/BUILD/rebar-2.6.4+git20180201.b6d3094: rebar_abort,erlang-rebar-testsuite
4,memory_allocator.h:119:15: error: 'sys_mmap' was not declared in this scope memory_allocator.h:145:7: error: 'sys_munmap' was not declared in this scope; did you mean 'munmap'?,EternalTerminal
1,"src/execstack: ""test""'s architecture is not supported",execstack
4,uninit.c:302:17: error: '_FPU_MASK_IM' undeclared (first use in this function),f2c
1,/home/abuild/rpmbuild/BUILD/fdo-client-1.0.0+git20210816.baa09b5/crypto/openssl/openssl_key_exchange_ecdh.c:508:9: error: 'EC_POINT_get_affine_coordinates_GFp' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]    508 |         if (EC_POINT_get_affine_coordinates_GFp(group  Sh_se_point  Shx_bn ,fdo-client
5,[ 2442.198534][ T8997] Out of memory: Killed process 8950 (Setup) total-vm,ghc-authenticate-oauth
5,[ 3028.161795][T10708] Out of memory: Killed process 10661 (Setup) total-vm,ghc-citeproc
5,[ 1968.000306][ T7607] Out of memory: Killed process 7560 (Setup) total-vm,ghc-cryptonite-conduit
5,[ 3479.90606][T9641] Out of memory: Killed process 9605 (Setup) total-vm,ghc-dhall
5,[ 1726.067221][ T5580] Out of memory: Killed process 5580 (ghc) total-vm,ghc-ed25519
5,[ 2808.591447][ T9619] Out of memory: Killed process 9539 (Setup) total-vm:,ghc-feed
5,[ 2291.069182][ T8378] Out of memory: Killed process 8331 (Setup) total-vm,ghc-hedgehog
5,[ 2332.020837][ T8747] Out of memory: Killed process 8689 (Setup) total-vm,ghc-hslua-module-doclayout
5,[ 1373.695587][ T6235] Out of memory: Killed process 6199 (Setup) total-vm,ghc-kan-extensions
1,error: line 62: Version required: Requires:       ghc-compiler = Building target platforms: riscv64-suse-linux Building for target riscv64-suse-linux,ghc-pandoc-lua-marshal
5,[ 4869.188984][T15464] Out of memory: Killed process 15417 (Setup) total-vm,ghc-sandwich
5,[ 3657.404595][T11779] Out of memory: Killed process 11699 (Setup) total-vm,ghc-skylighting-core
1,error: line 43: Version required: Requires:       ghc-compiler = Building target platforms: riscv64-suse-linux Building for target riscv64-suse-linux,ghc-tasty-hunit
5,[ 1919.243355][ T7313] Out of memory: Killed process 7255 (Setup) total-vm,ghc-tasty-quickcheck
5,[ 2294.193399][ T8513] Out of memory: Killed process 8466 (Setup) total-vm,ghc-turtle
5,[ 3810.194259][T13007] Out of memory: Killed process 9949 (Setup) total-vm,ghc-wai-app-static
5,[ 3087.889015][T10606] Out of memory: Killed process 10548 (Setup) total-vm,ghc-xml-hamlet
3,make[4]: *** [Makefile:723: test-suite.log] Error 1 make[3]: *** [Makefile:831: check-TESTS] Error 2,gphoto
2,ValueError: LDAP Setup failed,gssproxy
2,error: failed to run custom build command for `ring v0.16.20`,gstreamer-plugins-rs
1,g++: error: unrecognized command-line option ‘-msse2’ g++: error: unrecognized command-line option ‘-mfpmath=sse’,guitarix
6,make: *** [Makefile:169: all] Error 2,hashlink
6,1 out of 1 hunk FAILED -- saving rejects to file vendor/nix/.cargo-checksum.json.rej patching file vendor/nix/src/sys/ioctl/linux.rs Hunk #1 FAILED at 33. 1 out of 1 hunk FAILED -- saving rejects to file vendor/nix/src/sys/ioctl/linux.rs.rej,helvum
3,make[5]: *** [Makefile:1052: test-suite.log] Error 1 make[4]: *** [Makefile:1160: check-TESTS] Error 2,hfst
4,linux/trace.c:332:5: error: unknown type name 'HEADERS_STRUCT' linux/trace.c:444:17: error: 'MAX_INSTR_SZ' undeclared (first use in this function) linux/trace.c:444:13: error: unused variable 'buf' [-Werror=unused-variable],honggfuzz
1,"#error ""No support for this architecture (yet)""",howl
1,error: #error You are trying to use x86 context switching on a non-x86 platform. Your platform may be supported with the CMake option HPX_WITH_GENERIC_CONTEXT_COROUTINES=ON.,hpx
4,turnrest.c:164:9: error: void value not ignored as it ought to be    164 |         curl_easy_setopt(curl  api_http_get ? CURLOPT_HTTPGET : CURLOPT_POST  1);,janus-gateway
2,error: failed to run custom build command for `ring v0.16.20`,juliaup
4,error[E0425]: cannot find value `AVG_RANGE_COMP_REQ` in this scope error[E0425]: cannot find value `AVG_RANGE_COMP_REQ` in this scope,kanidm
1,kBuild/env.sh: unknown cpu/arch - riscv64,kbuild
1,# error Unsupported architecture,kcov
2,"error: #error ""No default crashkernel reservation for your architecture!"" error: 'CAN_REDUCE_CPUS' was not declared in this scope error: 'DEF_RESERVE_KB' was not declared in this scope; did you mean 'ADD_RESERVE_KB'?",kdump
3,"FAIL	github.com/keybase/client/go/kbfs/test	600.701s",keybase-client
3,Errors while running Ctest,kicad
8,touch: cannot touch '_output/bin/prerelease-lifecycle-gen': No such file or directory,kubernetes1.20
8,touch: cannot touch '_output/bin/prerelease-lifecycle-gen': No such file or directory,kubernetes1.21
8,touch: cannot touch '_output/bin/prerelease-lifecycle-gen': No such file or directory,kubernetes1.22
8,touch: cannot touch '_output/bin/prerelease-lifecycle-gen': No such file or directory,kubernetes1.23
8,touch: cannot touch '_output/bin/prerelease-lifecycle-gen': No such file or directory,kubernetes1.24
2,error: failed to run custom build command for `ring v0.16.20`,kubie
3,make[5]: *** [Makefile:973: test-suite.log] Error 1 make[4]: *** [Makefile:1081: check-TESTS] Error 2,lasso
4,src/config.h:365:53: error: unknown type name 'La_regs' src/audit.c:134:49: error: unknown type name 'La_retval',latrace
4,../govirt/ovirt-utils.c: In function ‘ovirt_rest_xml_node_get_str_array_from_path’: ../govirt/ovirt-utils.c:137:9: error: cast increases required alignment of target type [-Werror=cast-align],libgovirt
4,/home/abuild/rpmbuild/BUILD/libjxl-0.8.1/lib/jxl/enc_xyb.cc:223:21: error: variable 'std::atomic<bool> ok' has initializer but incomplete type    223 |   std::atomic<bool> ok{true};,libjxl
1,CMake Error at CMakeLists.txt:82 (message):    Unknown or unsupported processor: riscv64.  Override by setting    OQS_PERMIT_UNSUPPORTED_ARCHITECTURE=ON,liboqs
2,LifeLines requires a curses implementation with wide character support! + make -j16 make: *** No targets specified and no makefile found.  Stop.,lifelines
2,configure: error: Package requirements (luajit) were not met: Package 'luajit'  required by 'virtual:world'  not found,love
4,error: 'class Quotient::AccountSettings' has no member named 'accessToken'; did you mean 'clearAccessToken'?,matrix-quaternion
3,error: 1 target failed:      `--test alternative_backends`,mdbook
3,# Ran 220 tests  10 skipped  18 failed.,mercurial-extension-hg-evolve
8,"CMake Error at cmake/Modules/FindLua.cmake:27 (add_subdirectory):    add_subdirectory given source ""lib/lua"" which is not an existing directory.",minetest
4,pkg/drivers/kvm/domain.go:67:53: undefined: domainTmpl,minikube
4,dns_utils.cpp:590:22: error: 'record_count' was not declared in this scope dns_utils.cpp:597:23: error: 'good_record' was not declared in this scope; did you mean 'good_records'?,monero
1,net_ssl.cpp:216:35: warning: 'EC_KEY* EC_KEY_new()' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations],monero-gui
8,cp: cannot stat './../../class/lib/build-linux/tmp/gensources.exe': No such file or directory,mono-core
4,SelfSignedCertificate.cpp:45:29: error: 'CRYPTO_MEM_CHECK_ON' was not declared in this scope SelfSignedCertificate.cpp:45:13: error: 'CRYPTO_mem_ctrl' was not declared in this scope; did you mean 'CRYPTO_memcmp'?,mumble
1,"Makefile:144: *** CPU type ""riscv64"" not supported.  Please file bug report at 'https://github.com/mupen64plus/mupen64plus-core/issues'.  Stop.",mupen64plus
2,Run-time dependency luajit found: NO (tried pkgconfig and cmake),naev
2,error: failed to run custom build command for `ring v0.16.20`,ncspot
5,c++: internal compiler error: Segmentation fault signal terminated program cc1plus,neochat
4,simd_generic.hpp:324:56: error: cannot convert 'const ngcore::SIMD<double  1>' to 'double' in initialization,netgen
4,src/poddlthread.cpp:65:31: error: 'CURLOPT_PROGRESSFUNCTION' is deprecated: since 7.32.0. Use CURLOPT_XFERINFOFUNCTION [-Werror=deprecated-declarations],newsboat
8,install: cannot stat 'nmon': No such file or directory,nmon
2,vendor/golang.org/x/exp/shiny/driver/x11driver/buffer.go:111:9: undefined: shmClose vendor/golang.org/x/exp/shiny/driver/x11driver/screen.go:328:23: undefined: shmOpen, noisetorch
2,CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):    Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR),nomacs
6,CMakeFiles/Makefile2:2682: CMakeFiles/notcurses.3.man.dir/all] Error 2,notcurses
8,cpio: gcc-9.2.1+git749/libgcc/libgcc2.c: Cannot stat: No such file or directory,ocserv
8,make[3]: *** No rule to make target 'param.riscv64_linux26.h'  needed by 'param.h.new'.  Stop.,openafs
3,"The following tests FAILED: 	 82 - test_regressions_1 (Subprocess killed) 	 83 - test_regressions_221 (Subprocess killed)  	213 - inchiSteffen_PubChem.smi_Test (Timeout) 	215 - pytest_sym (Timeout) 	223 - pybindtest_bindings (Failed) Errors while running CTest",openbabel
6,No buildstatus set  either the base system is broken (kernel/initrd/udev/glibc/bash/perl) or the build host has a kernel or hardware problem…,openjfx8
4,operf_utils.cpp:1423:2: error: 'rmb' was not declared in this scope,oprofile
4,base64.c:89:36: error: 'i' may be used uninitialized [-Werror=maybe-uninitialized] base64.c:94:20: error: 'skip' may be used uninitialized [-Werror=maybe-uninitialized],pam_p11
2,error: failed to run custom build command for `ring v0.16.20`,parsec
2,error: failed to run custom build command for `ring v0.16.20`,parsec-tool
8,make: *** No rule to make target 'include/generic/Types.inc'  needed by 'api/thunks.o'.  Stop.,perl-Prima
6,Fatal SIMPLE-ERROR:    please implement make: *** [Makefile:47: bin/pgloader] Error 1,pgloader
1,dhparam: Unknown option: -C dhparam: Use -help for summary.,pound
1,libglfork.cpp:1028:6: error: ifunc is not supported on this target,primus
1,"/usr/lib64/python3.11/random.py:436: in sample      raise TypeError(""Population must be a sequence.  "" E   TypeError: Population must be a sequence.  For dicts or sets  use sorted(d).",python-ansiwrap
1,"AssertionError: '[mp4] muxer does not support non seekable output' not found in ""no container format 'mp4'""",python-av
6,ConnectionRefusedError: [Errno 111] Connection refused,python-avro
4,stdalign_check.c:13:9: error: unused variable ‘alignment’ [-Werror=unused-variable] stdalign_check.c:9:24: error: unused variable ‘test’ [-Werror=unused-variable],python-awscrt
6,Badness 1000 exceeds threshold 999  aborting,python-azure-communication-networktraversal
6,Badness 1000 exceeds threshold 999  aborting,python-azure-mgmt-recoveryservicessiterecovery
6,Badness 1000 exceeds threshold 999  aborting,python-azure-mgmt-servicefabricmanagedclusters
6,Badness 1000 exceeds threshold 999  aborting,python-azure-multiapi-storage
6,Badness 1000 exceeds threshold 999  aborting.,python-brewer2mpl
3,FAILED test_runtime.py::RuntimeGoingWrongTestCase::test_duplication_and_runtime_malformed,python-calmjs
4,AttributeError: module 'inspect' has no attribute 'getargspec',python-cepa
4,TypeError: tuple indices must be integers or slices  not str TypeError: __dict__ must be set to a dictionary  not a 'NoneType',python-cerealizer
3,cpplint_unittest.py:6501: AssertionError,python-cpplint
3,tests/test_subprocess.py:84: AssertionError,python-curio
1,KeyError: 'INPLACE_ADD',python-cx_Freeze
8,cytoolz/dicttoolz.c:211:9: fatal error: longintrepr.h: No such file or directory,python-cytoolz
3,"FAILED test_datadiff.py::test_diff_set - assert ""--- x\n+++ y...n 3 \n 7 \n])... FAILED test_datadiff.py::test_diff_frozenset - assert ""--- x\n+++ y...n 3 \n …",python-datadiff
3,FAILED testing/test_metadata.py::TestBasenameMeta::test_noversion_sameproject FAILED testing/test_metadata.py::TestBasenameMeta::test_sort_sameproject_links,python-devpi-common
3,FAIL: testDiffMain (diff_match_patch.tests.diff_match_patch_test.DiffTest) AssertionError: False is not true,python-diff-match-patch
3,FAILED tests/test_django.py::TestStaticFiles::test_find_with_glob - re.error:... FAILED tests/test_django.py::TestStaticFiles::test_find_with_recursive_glob,python-django-assets
3,FAILED tests/test_handlers.py::AxesDatabaseHandlerTestCase::test_handler - As... FAILED tests/test_logging.py::AccessLogTestCase::test_log_data_truncated - ax…,python-django-axes
4,ERROR: test_view_dynamic (tagging.tests.tests.TestTaggedObjectList.test_view_dynamic) raise source.error('global flags not at the start ' re.error: global flags not at the start of the expression at position 14,python-django-tagging
8,editdistance/bycython.cpp:216:9: fatal error: longintrepr.h: No such file or directory,python-editdistance
4,packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier),python-efilter
8,efl/eo/efl.eo.c:248:9: fatal error: longintrepr.h: No such file or directory,python-efl
3,FAILED tests/test_node_pool.py::test_threading_test[1] - assert 4633 >= 10000 FAILED tests/test_node_pool.py::test_threading_test[8] - assert 3108 >= 10000,python-elastic-transport
3,FAILED eliot/tests/test_filter.py::MainTests::test_default - AttributeError: …,python-eliot
1,ImportError: cannot import name 'sre_parse' from 're' (/usr/lib64/python3.11/re/__init__.py),python-exrex
3,FAILED tests/test_pyi_files.py::test_pyi_file[tests/type_comments.pyi] - asse…,python-flake8-pyi
8,cc1: fatal error: frozendict/src/3_11/frozendictobject.c: No such file or directory,python-frozendict
3,FAILED test/test_holiday_base.py::TestAllInSameYear::test_all_countries - Att…,python-holidays
3,FAILED test_ece.py::TestEce::test_derive_key_invalid_mode - AttributeError: '…,python-http-ece
6,No buildstatus set  either the base system is broken (kernel/initrd/udev/glibc/bash/perl) [90344s] or the build host has a kernel or hardware problem…,python-i3ipc
3,FAILED influxdb/tests/client_test.py::TestInfluxDBClient::test_write_gzip - A…,python-influxdb
4,jp_exception.cpp:524:23: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘frame’; did you mean ‘cframe’? jp_exception.cpp:552:36: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’},python-JPype1
3,FAILED jsonweb/tests/test_decode.py::TestJsonWebObjectDecoder::test_bad__init__raises_error FAILED jsonweb/tests/test_decode.py::TestJsonWebObjectDecoder::test_class_kw_args_are_optional,python-JsonWeb
3,FAILED tests/unit/utils/test_scp.py::TestScp::test_scp_user_def_progress FAILED tests/unit/utils/test_scp.py::TestScp::test_scp_user_def_progress_args_2,python-junos-eznc
3,SKIPPED [1] test/test_admin_integration.py:13: ACL features require broker >=0.11 SKIPPED [1] test/test_admin_integration.py:89: Describe config features require broker >=0.11,python-kafka-python
3,FAILED kajiki/tests/test_ir.py::TestBasic::test - TypeError: code() argument ... FAILED kajiki/tests/test_ir.py::TestSwitch::test_basic - TypeError: code() ar…,python-Kajiki
4,_line_profiler.c:5627:46: error: invalid use of incomplete typedef ‘PyFrameObject’ {aka ‘struct _frame’},python-line_profiler
1,RuntimeError: Cannot install on Python version 3.11.1; only versions >=3.7 <3.11 are supported.,python-llvmlite
8,lws.bycython.cpp:196:9: fatal error: longintrepr.h: No such file or directory,python-lws
3,FAIL: test_Cookie_iterator (test.test_cookies.CookieTests.test_Cookie_iterator),python-mechanize
2,error: failed to run custom build command for `ring v0.16.20`,python-mitmproxy-wireguard
3,FAILED tests/test_compute_hash.py::TestComputeHash::test_ntowfv1 - ValueError... FAILED tests/test_compute_hash.py::TestComputeHash::test_ntowfv2 - ValueError…,python-ntlm-auth
4,pybind11.h:1892:14: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’},python-openmesh
3,ERROR: test_is_legacy_version (tests.test_version.TestOpenwrtLuciRPC) Test comparing versions works as expected.,python-openwrt-luci-rpc
4,TypeError: not all arguments converted during string formatting,python-oslo.policy
4,TypeError: not all arguments converted during string formatting,python-oslo.versionedobjects
3,ERROR parsimonious/tests/test_benchmarks.py ERROR parsimonious/tests/test_expressions.py ERROR parsimonious/tests/test_grammar.py ERROR parsimonious/tests/test_nodes.py,python-parsimonious
3,FAILED test/test_filepath.py::Test_validate_filepath::test_exception_invalid_char[17DOJ6bKqfdiULG0LywrS37oFh7LAmeHJJyGieLRVf4xjHkenEuiBa8P0zwknBE1\x0017DOJ6bKqfdiULG0LywrS37oFh7LAmeHJJyGieLRVf4xjHkenEuiBa8P0zwknBE1] FAILED test/test_filepath.py::Test_sanitize_filepath::test_normal_str[universal-AA\x00B--AAB0],python-pathvalidate
3,FAILED tests/test_cli_sync.py::test_force_files_with_dot_in_extension - asser... FAILED tests/test_cli_sync.py::test_pip_install_flags[cli_flags6-expected_install_flags6],python-pip-tools
3,FAILED tests/test_local.py::TestLocalMachine::test_iter_lines_timeout - asser…,python-plumbum
1,Sorry  but pony 0.7.16 requires Python of one of the following versions: 3.6-3.10. You have version 3.11.1,python-pony
4,ValueError: invalid mode: 'U',python-pprintpp
3,FAILED pscript/tests/test_parser1.py::TestExpressions::test_import - Assertio…,python-pscript
8,E: [pulseaudio] core-util.c: Failed to connect to system bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory E: [null-sink] util.c: Failed to connect to system bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory,python-pulsectl
4,pyblake2module.c:699:27: error: lvalue required as left operand of assignment,python-pyblake2
3,FAILED pyct/tests/test_report.py::test_report_gives_package_version - Asserti…,python-pyct
3,FAILED tests/test_build.py::test_logo - assert [],python-pydata-sphinx-theme
8,pyemd/emd.cpp:200:9: fatal error: longintrepr.h: No such file or directory,python-pyemd
8,src_c/pypm.c:209:9: fatal error: longintrepr.h: No such file or directory,python-pygame
3,FAILED kmip/tests/unit/services/server/crypto/test_engine.py::TestCryptographyEngine::test_mac_with_cryptographic_failure,python-PyKMIP
3,FAILED tests/test_pyp.py::test_examples - pyp.PypError: Code raised the follo... FAILED tests/test_pyp.py::test_user_error - AssertionError: Regex pattern did…,python-pyp
3,FAILED tests/test_i18n.py::TestTranslations::test_ldgettext - AttributeError:... FAILED tests/test_i18n.py::TestTranslations::test_ldngettext - AttributeError…,python-pyramid
1,AttributeError: module 'numpy' has no attribute 'float',python-pyreadstat
3,SKIPPED [1] tests/PyroTests/test_naming2.py:342: dbm must be available SKIPPED [1] tests/PyroTests/test_naming2.py:100: dbm must be available,python-Pyro4
3,FAILED scss/tests/test_expression.py::test_reference_operations - re.error: g... FAILED scss/tests/test_expression.py::test_functions - scss.errors.SassSyntax…,python-pyScss
8,Modules/_sha3/backport.inc:78:10: fatal error: pystrhex.h: No such file or directory,python-pysha3
3,FAILED ../tests/test_cap_operations.py::test_iterate_empty_psml_capture - ass…,python-pyshark
3,FAILED test_junit_classname.py::flake-8::FLAKE8 - AttributeError: 'Applicatio…,python-pytest-flake8
1,_pycrfsuite.cpp:18056:23: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’ _pycrfsuite.cpp:18058:23: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’,python-python-crfsuite
3,FAILED tests/test_scheduler.py::SchedulerTestCase::test_04_schedule_ten - Ass…,python-python-crontab
8,src/_rtmidi.cpp:243:9: fatal error: longintrepr.h: No such file or directory,python-python-rtmidi
4,ERROR: testQuotes (pytils.test.test_typo.RulesTestCase.testQuotes) Unit-test for quotes rule re.error: global flags not at the start of the expression at position 14,python-pytils
3,FAILED test/test_pytools.py::test_obj_array_vectorize - AttributeError: modul…,python-pytools
8,src/quicktions.c:209:9: fatal error: longintrepr.h: No such file or directory,python-quicktions
8,sasl/saslwrapper.cpp:196:9: fatal error: longintrepr.h: No such file or directory,python-sasl
6,error: subprocess-exited-with-error error: metadata-generation-failed,python-scipy
6,Badness 1132 exceeds threshold 999  aborting,python-securesystemslib
4,siplib.c:13750:22: error: invalid use of undefined type 'struct _frame',python-sip4
4,AttributeError: type object 'op' has no attribute 'pop_jump_if_true',python-skyfield
3,FAILED tests/test_path.py::TestPath::test_read_text - ValueError: invalid mod... FAILED tests/test_util.py::TestSphinxTesting::test_TestApp_when_copy_srcdir_to_tmpdir,python-sphinx-testing
1,utilsextension.c:22347:24: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_type’ utilsextension.c:22349:22: error: ‘_PyErr_StackItem’ {aka ‘struct _err_stackitem’} has no member named ‘exc_traceback’,python-tables
3,/var/tmp/rpm-tmp.o4A8wa: line 233:  6662 Segmentation fault      PYTHONPATH=${PYTHONPATH:+$PYTHONPATH:}/home/abuild/rpmbuild/BUILDROOT/python-tesserocr-2.5.2-3.2.riscv64/usr/lib/python3.8/site-packages PYTHONDONTWRITEBYTECODE=1 pytest-3.8 --ignore=_build.python38 --ignore=_build.python39 --ignore=_build.python311 --ignore=_build.python310 -v -k 'not test_LSTM_choices',python-tesserocr
3,ERROR test_aio.py - AttributeError: module 'asyncio' has no attribute 'corout... ERROR test_buffered_transport.py - AttributeError: module 'asyncio' has no at…,python-thriftpy2
3,FAILED test/test_as_future.py::test_as_future_coroutine[asyncio] - ImportErro... FAILED test/test_call_later.py::test_explicit_reactor_coroutine[asyncio] - Im…,python-txaio
3,FAILED tests/testsuite.py::XMLTestRunnerTestCase::test_basic_unittest_constructs FAILED tests/testsuite.py::XMLTestRunnerTestCase::test_unexpected_success - A…,python-unittest-xml-reporting
1,ERROR: test_coroutine_error (urwid.tests.test_event_loops.AsyncioEventLoopTest.test_coroutine_error) AttributeError: module 'asyncio' has no attribute 'coroutine',python-urwid
4,ERROR test_whatever.py - TypeError: code expected at least 16 arguments  got 14,python-whatever
3,FAILED tests/test_callable.py::test_callable_attributes - AttributeError: typ... FAILED tests/test_wire.py::test_default_wire - AttributeError: type object 'm…,python-wirerope
1,ERROR pytest/test_std.py - KeyError: '3.11',python-xdis
3,FAILED tests/test_xkcdpass.py::TestEntropyInformation::test_entropy_printout_valid_input,python-xkcdpass
3,Error in test test_with_syslog (ZConfig.components.logger.tests.test_logger.TestConfig.test_with_syslog) AttributeError: module 'socket' has no attribute 'SocketError',python-Zconfig
5,g++: internal compiler error: Segmentation fault signal terminated program cc1plus,qbs
8,types.h:11:10: fatal error: quadmath.h: No such file or directory,qcdloop
6,Error: unable to perform an operation on node 'rabbit@localhost'. Please see diagnostics information and suggestions below.,rabbitmq-c
3,"The following tests FAILED:  	 16 - exhaustive1_test (Timeout) 	 17 - exhaustive2_test (Timeout) 	 19 - exhaustive_test (Timeout) Errors while running Ctest",re2
1,NoMethodError: undefined method `exists?' for File:Class,rubygem-passenger
6,1 out of 1 hunk FAILED -- saving rejects to file vendor/tss-esapi-sys/.cargo-checksum.json.rej,rust-keylime
2,error: failed to run custom build command for `ring v0.16.20`,rustscan
6,error: Bad exit status from /var/tmp/rpm-tmp.iMySza (%build),sbcl
1,scitokens_internal.cpp:59:90: error: 'void EC_KEY_free(EC_KEY*)' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations] scitokens_internal.cpp:520:51: error: 'const EC_POINT* EC_KEY_get0_public_key(const EC_KEY*)' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations] scitokens_internal.cpp:527:45: error: 'int EC_POINT_get_affine_coordinates_GFp(const EC_GROUP*  const EC_POINT*  BIGNUM*  BIGNUM*  BN_CTX*)' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations],scitokens-cpp
4,GNUmakefile:67: *** multiple target patterns.  Stop.,seamonkey
3,make[6]: *** [Makefile:820: test-suite.log] Error 1 make[5]: *** [Makefile:928: check-TESTS] Error 2,softhsm
2,CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):    Could NOT find LuaJIT (missing: LUAJIT_LIBRARY LUAJIT_INCLUDE_DIR),solarus
1,../../utils/parse_plt.h:134:2: error: #error Unknown architecture    134 | #error Unknown architecture,spindle
6,make: *** [Makefile:159: all] Error,stellarium
2,configure: error: Package requirements (luajit) were not met: Package 'luajit'  required by 'virtual:world'  not found,sysbench
4,/home/abuild/rpmbuild/BUILD/thinkfan-1.3.1/src/fans.cpp:192: undefined reference to `__atomic_fetch_sub_1',thinkfan
2,error: failed to run custom build command for `ring v0.16.20`,tiny
1,../src/tup/platform.c:64:2: error: #error Unsupported cpu architecture. Please add support in tup/platform.c 64 | #error Unsupported cpu architecture. Please add support in tup/platform.c,tup
2,[92m *[0m Checking for Zlib... [91m *[0m Configure failed. error was: undefined method `exists?' for File:Class,tupitube
1,cc: error: '-march=native': ISA string must begin with rv32 or rv64 CMake Error at CMakeLists.txt:174 (string):,vectorscan
3,"Failures:  	From test_vim9_script.vim: 	Found errors in Test_reject_declaration(): 	Caught exception in Test_reject_declaration(): Vim(call):E109: Type mismatch; expected list<number> but got list<any> @ command line..script /home/abuild/rpmbuild/BUILD/vim-9.0.1307/src/testdir/runtest.vim[569]..function RunTheTest[52]..Test_reject_declaration[2]..Run_test_reject_declaration[1]..RunVimInTerminal[58]..TermWait[9]..<SNR>272_Exit_cb  line 3",vim
6,make: *** [Makefile:159: all] Error 2,warzone2100
2,CMake Error at src/plugins/CMakeLists.txt:116 (message):    Ruby not found,weechat
2,error: failed to run custom build command for `ring v0.16.20`, wezterm
1,"lj_arch.h:424:2: error: #error ""No target architecture defined""    424 | #error ""No target architecture defined""",wrk
5,c++: fatal error: Killed signal terminated program cc1plus,wyrmgus
4,pki_key.cpp:780:53: error: invalid conversion from 'const dsa_st*' to 'DSA*' {aka 'dsa_st*'} [-fpermissive],xca
4,parse.c:138:10: error: cast increases required alignment of target type [-Werror=cast-align]    138 |   return (XdgDirEntry *)g_array_free (array  FALSE);,xdg-user-dirs-gtk
4,regsmi.h:67:2: error: implicit declaration of function 'outb' [-Werror=implicit-function-declaration] regsmi.h:68:9: error: implicit declaration of function 'inb' [-Werror=implicit-function-declaration],xf86-video-siliconmotion
4,/home/abuild/rpmbuild/BUILD/xmrig-6.18.1/src/crypto/cn/asm/CryptonightR_template.S:6: Error: unknown pseudo-op: `.intel_syntax',xmrig
1,"lj_arch.h:472:2: error: #error ""No target architecture defined""      472 | #error ""No target architecture defined""",xplr
8,Error running (['dpkg-query'  '--showformat=${Version}'  '--show'  'xserver-xorg-video-dummy'] ) {'stdout': -1  'stderr': -1  'universal_newlines': True}: [Errno 2] No such file or directory: 'dpkg-query',xpra
6,make[1]: *** [CMakeFiles/Makefile2:263: CMakeFiles/stage3.dir/all] Error 2 make: *** [Makefile:139: all] Error 2,zig
